### ISSUE TITLE
Spike - Can we enable SSO in native web browser cookies

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#10035]
## Proposed Change

Take a look at our current SSO enablement and see if there is a library/native browser import we can use to supply similar functionality to an browser throw out.

## Why Should We Prioritize?

Would streamline SSO better

## Coding Time Estimation

3 (Timeboxed to 1 day intentionally)
	
## Checklist
- [x] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by theodur** [comment]
After doing some research on this, it's not possible to directly set cookies in a user's native browser app. This is due to sandboxing and security reasons. One of the few ways to launch a user to their external browser while having them maintain their session would be to pass some type of session identifying query parameter in the URL that the user is being to.

This would require a few things to make this work:

1. The VA.gov frontend would need to be updated to parse query parameters in the URL to retrieve a session ID, and then set the user's session manually.
2. The API would need to be updated to provide a field to the mobile client that is safe to use as a query parameter for the session when launching user's to their external browser. This is a large security concern though, because in theory someone could share the link containing the session query parameter, and whoever has access to that link would be able to use the site based on that user's session.

Both of those required changes would be outside our domain, and would involve the identity team. It seems like for now, using WebViews for SSO is the best option without adding any extra complexity or overhead.

**Comment by theodur** [comment]
Moved this to the code review lane to signify this in no longer in progress and is in the review stage, even though there's no PR or code associated with this ticket.

**Comment by theodur** [comment]
After reaching out to the identity team and discussing the approach of using a session ID query parameter in external links, it turns out this is not possible at the moment. This is due to the business requirement of having authentication modality between va.gov and the MyHealtheVet site. Currently, other sites do not have integration with SSO, so if a session was spawned in the browser based off the mobile app's SSO authentication, user's wouldn't be authenticated on MyHealtheVet pages.

MyVAHealth is planning on adding support for integrating with other clients. When this happens, the session ID parameter route may be possible.

The identity team mentioned they are in the early stages of investigating passkeys, which may even remove the need for this ticket entirely, since passkeys would make it seamless for users to sign in to the browser with biometrics. We will follow up with the investigation on this work, but for now, this ticket is not possible to do.

**Note**: I'll update this comment with a link to the passkey ticket or epic if the identity provides one.
