### ISSUE TITLE
Spike: Identify which elements of an authenticated Webview can be modified by the mobile app

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#10218]
**Acceptance Criteria**:

Determine which elements of an authenticated Webview page can be modified by the mobile app/team. Examples of Webview elements to assess:
- Header
- Footer
- Back navigation
- Navigation bar
- Dark mode
- Font sizing

**Comment by alexandec** [comment]
## Findings

Existing INJECTED_JAVASCRIPT which partially works and partially fails:

```
const INJECTED_JAVASCRIPT = `(function() {
  localStorage.setItem('hasSession', true);
  document.getElementsByClassName("header")[0].style.display='none';
  document.getElementsByClassName("va-nav-breadcrumbs")[0].style.display='none';
  document.getElementsByClassName("footer")[0].style.display='none';
})();`
```

I investigated how to improve the injected JS to get it fully working, and to remove/change additional elements. I used the feature/9583-EnableSSOAppWide branch for testing purposes.

Below I've listed the elements I examined, with findings for each.

### Header

Existing code works fine to hide the header, but using getElementsByTagName should be more efficient.

### Footer

Existing code works fine to hide the footer, but using getElementsByTagName should be more efficient.

### Back navigation

Existing JS code does not work to hide the breadcrumbs. This is because the header has been transitioned to use the va-breadcrumbs web component. The existing selector targets the va-nav-breadcrumbs class which no longer exists. New code needed:

```
document.getElementsByTagName('va-breadcrumbs')[0].style.display='none'
```

On the Notification Settings page, this needs to be run only after the page has finished loading. See code below.

### Navigation bar

This hides the mobile navigation bar:

```
document.getElementsByClassName('mobile-nav')[0].style.display='none';
```

On the Notification Settings page, this needs to be run only after the page has finished loading. See code below.

### Dark mode

va.gov does not have a dark mode. Even if the app is in dark mode, the website will keep its existing light mode.

### Font sizing

Font size can be modified with:

```
document.getElementsByTagName('html')[0].style.fontSize='${useFontScale()(1)}rem';
```

This will automatically adjust, relative to the base font size, based on the user's text size setting.

## Solution

Proper timing is needed to hide some elements on the Notification Settings page. It's necessary to wait until the loading indicator is removed to ensure the scripts on the page have completed and everything is rendered. A MutationObserver allows this.

```
const INJECTED_JAVASCRIPT = `(function() {
  localStorage.setItem('hasSession', true);

  // Set font size based on user's font size setting in the app
  document.getElementsByTagName('html')[0].style.fontSize='${useFontScale()(1)}rem';

  // Hide certain elements immediately on load
  document.getElementsByTagName('header')[0].style.display='none';
  document.getElementsByTagName('footer')[0].style.display='none';

  // These elements don't exist on load. Wait and hide them after they appear
  const hideAsyncElements = () => {
    document.getElementsByClassName('mobile-nav')[0].style.display='none';
    document.getElementsByTagName('va-breadcrumbs')[0].style.display='none';
  }

  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      mutation.removedNodes.forEach((node) => {
        if (node.tagName === 'VA-LOADING-INDICATOR') {
          hideAsyncElements();
        }
      });
    });
  });

  observer.observe(document.body, { childList: true, subtree: true });
})();`
```

**Comment by dumathane** [comment]
@alexandec great notes. Only ask I have is could you please include a before/after video of the push notifications page?

**Comment by alexandec** [comment]
Before:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGIvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96f6e48efcb1a2959ef71dddfcc30c39191492f3/notifications-webview-before.mp4)

After:


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGYvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31ab74b49a7484ed6a50f6e6f8f5d69df346d1a8/notifications-webview-after.mp4)

Text size adjustment (after):


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHovQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53b7b6d3d6cece1a6604836512daf86ccfc0fdf3/text-size-adjustment-after.mp4)

**Comment by alexandec** [comment]
## Simplified solution

Based on a suggestion from @timwright12, here's a simplified approach that injects CSS into the page to hide the elements. This eliminates the complexity of using a MutationObserver to check when loading is finished and elements are present. Instead the browser takes care of that.

```
const css = `
  html { font-size: ${useFontScale()(1)}rem; }
  header, footer, va-breadcrumbs, .mobile-nav { display: none; }
`

const INJECTED_JAVASCRIPT = `(function() {
  localStorage.setItem('hasSession', true);
  const styleElement = document.createElement('style');
  styleElement.innerHTML = \`${css}\`;
  document.head.appendChild(styleElement);
})();`
```

**Comment by dumathane** [comment]
Closing! Thanks Chris.
