### ISSUE TITLE
BUG - sev-3 - All - Claims: completed file requests in list read like non-completed file requests to screen readers

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4761]
## What happened?

For a non-sighted screen reader user, there's no difference between the completed rows for file requests, and the uncompleted ones. See the screenreader caption at the bottom of this screenshot - where we miss the mark twice, by 1) not reading out the 'completed' checkmark, and 2) still telling them to "go to the file request details page to upload file". 

The sighted user equivalent - it's like if we got rid of the completed checkmark icon and just had a list of files. You'd have to open each one to figure out which one is the 'one file request' left from the VA.

![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/613e4443-14aa-4938-b76d-2a76bab92173)

## Specs:

- Device:
- OS: both iOS and Android
- User Account: Accounts with file requests -- demo mode (3rd claim?) or arfan.a.russel1 (4th or 5th claim)
- Accessibility State: screen reader on

## Steps to Reproduce

Claims > [claim with file request] > Review file requests

## Desired behavior

Ideas for a fix: include 'completed' (like the claims step row does, screenshot below), or change the button callout to "review uploaded file details", or both. @brea11y to weigh in.

![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/a3d16e40-be43-44ba-924c-9aaf4c4ec050)

_I could have sworn that we've talked about this before as a team, but I can't find a ticket for it (not even a closed one) and the history of the File Request screen code doesn't look like it was fixed then broken. Maybe I'm thinking about the larger claim file request conversation that's poorly contained in this enhancement ticket #2734?_

## Acceptance Criteria

- [ ] Include "completed" like we are doing in the claims step row (to help keep the experience is consistent)
   - Ideally, this would read  as "Request 1 of 5 completed"
- [ ] Update button copy / label to read as "review uploaded file details"
   - Currently, the entire screenreader copy says "Request 4, Button, Go to the file request details page to upload file". It would make more sense for it to read as "Request 4 of 5 completed. Review uploaded file details."

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

- 3 - Medium

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Estimate of 1 added

**Comment by bischoffa** [comment]
Blocked by UX review. No ETA on the work and it's prioritization.

**Comment by bischoffa** [comment]
Blocked - work needed to unblock this ticket, is in current sprint.

**Comment by bischoffa** [comment]
Ticket blocking this was completed. Moving this to backlog ready to work - meaning it just needs prioritized to be worked :)

**Comment by theodur** [comment]
@brea11y When I looked into this, it looks like the request name doesn't always follow the format "Request #". For instances when it's formatted differently, e.g `Exam Request - Request for Clarification`, are we okay to have the screen reader say the "Request 1 of 5 completed" part before saying the actual request name? This is what that would sound like:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/5a179c3f-d0ea-4c3a-bcdc-95c098a78779

Also, in the video, you'll notice that rather than VoiceOver saying "Request 1 of 5 completed," it says "uploaded" instead. This is because file requests are different from claim status steps, because a request being uploaded doesn't necessarily mean the request is complete. Requests can have different statuses like `SUBMITTED_AWAITING_REVIEW`, `NO_LONGER_REQUIRED`, etc. So it may be confusing to users if the screen reader says "completed" if the request is just uploaded rather than complete. The green check mark we display next to the request signifies it's been uploaded rather than complete, which is why I updated the screen reader to say "uploaded" also. Is this okay, or did you want us to stick with "completed" at the end?

For requests that aren't completed, I made an update to have the screen reader say `needed` at the end of the "Request 1 of 5" part, to show that it still needs to be uploaded, since we're mentioning when it's been uploaded for requests that have the checkmark. This may make it easier for to know the difference between the requests when navigating through the list. Is that okay, or should we leave that out? Here's what that looks like:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/48715d68-b2d1-4854-a48e-80cd072dacff

Didn't realize this comment would end up being this long 😅. To summarize:

1. For instances where the request name doesn't follow the format `Request #` are we okay to have the screen reader say "Request 1 of 5 completed" before saying the request name?
2. Are we okay to update "completed" to "uploaded" at the end of the label?
3. Are we okay to add "needed" at the end of the label when a request hasn't been uploaded?

**Comment by brea11y** [comment]
Hey @theodur – Sorry for the delay on getting back to you and absolutely no worries about the length of the comment. I love having all of the details, when possible!   
 

1.  Yes, we can absolutely have the “Request X of X ....” prior to the actual request name.
2.  It is also okay to say uploaded vs. completed. I agree that hearing completed could be confusing. 
3.  I really like the addition of “needed” at the end of the uncompleted requests. That sounds great to me! Anytime we can give more clarity, the better. Thanks for doing this!

Please let me know if there is anything else that I can help with! Great work on this!

**Comment by theodur** [comment]
@brea11y No problem at all, and thanks for confirming those changes are good! I'll go ahead and open the PR for this. I'll let you know if anything else comes up 🙂

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by TKDickson** [comment]
Does not require retesting in develop; closing.
