### ISSUE TITLE
Improve QA Charles Proxy documentation

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5002]
Our current Charles Proxy documentation lives on the [resources page](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/Resources/) of the main documentation site.

This documentation largely lives in google docs instead of within the main documentation site.

**To Do**

- Create a "tools" section in the doc site (if one isn't created)
- Move Charles Proxy to it's own section
- Review, update, and migrate all google doc documentation into the actual documentation site.
- Deprecate the old google docs with a link to the new location.

**Comment by TKDickson** [comment]
I have to redo all of my certificates this sprint, and yes that's as painful as it sounds, so I'm taking over this ticket. Reassigning to me and removing Tom. @DJUltraTom you can add PR review comments if what I end up writing doesn't cover something you had thought about.

**Comment by TKDickson** [comment]
Also changing estimate down to a 2, since a lot of this exists in a public forum already & I'll be linking out to that instead of rewriting it.

**Comment by timwright12** [comment]
@bischoffa  Reopening this ticket to address the thress google docs we have linked in some Charles documentation: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/Resources#charles-proxy

We need those docs addressed and converted into actual doc site pages

**Comment by bischoffa** [comment]
Here is the Team's [Github Page ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Overall%20Team/QA%20Tool%20Setup/Charles%20Proxy)that has the CP info from the Content Library

**Comment by DJUltraTom** [comment]
Since this is a third party tool, I don't believe we need to create additional instruction tutorials. We created some basic information when we first introduced the tool to our testing arsenal, if only to add a personal touch of VA Mobile app specificity to our QA onboarding process. In the 3 years since we started the process of getting charles proxy approved for use in gov work and getting team members familiarized with it there have been MANY changes to the tool from the developer. Given that Charles proxy is continually being updated, leaving the act of documenting and updating the documentation should be left to the Company that creates charles proxy and we can always refer to the frequently updated and incredibly useful "Charles Docsy" site. Much in the same way we wouldn't write documentation for XCode or Android studio updates, we should not expend energy on documentation that exists elsewhere only to have it in another place on our servers that we will need to update and migrate to whatever flavor of documentation keeping we are utilizing as time marches on.

Created a document on Github with the following links for additional Charles Proxy support:
[Github Additional resource page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Overall%20Team/QA%20Tool%20Setup/Charles%20Proxy/Additional%20Resources.md)

Links contained:
https://charlesdocsy.com/
https://www.charlesproxy.com/documentation/welcome/
