### ISSUE TITLE
BUG - sev-3 - iOS - Certain elements throughout the app don't mesh well with iOS display increase

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5106]
## What happened?

Certain elements that are totally fine at the largest possible font size in iOS (even with accessibility sizes turned on) suddenly experience wrapping, cutoff, or overlap when you turn on display zoom in iOS, even at not-the-largest font size.

Examples include snackbars:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/a0ca9895-0483-4e14-b28f-802883c21ffb) 

Med status labels (label tags):
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/2e2688d2-8120-4cf8-b6dc-0466145f7702)

Action buttons:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/c9333bdd-cd7d-4a74-9ade-1274d9c06237)

And some header/back combos:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/4c26ac88-7266-4e6b-8c6b-763aa50ad276)

## Specs:

- Device: PHYSICAL device. I'm using an iPhone 13
- OS: iOS
- User Account:
- Accessibility State: Display zoom for iOS turned on, and font size increased

## Steps to Reproduce

![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/791b7334-1c9f-4f8b-9e96-2d8eda43ccd8)

Note that Dylan and I found earlier (with #5022) that it doesn't seem to be visible in in emulators/simulators. It has to be seen on a physical device.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Estimate of 1 added

**Comment by Sparowhawk** [comment]
@TKDickson does this only occur when you turn on display zoom after already being in the app? or does that not matter and it is broken if display zoom is on before you enter the app?

I ask because there is no built in way for us to determine if display zoom is on or not.

What I can do is either create a list of devices that we would have to update each year as iPhone releases new phones with their screen height and compare to the device screen height to determine if zoom is on. Or I can save their original screen height when they enter the app and then compare when/if they change display zoom based on the height going down or up.

The second option only will really work if display zoom isn't an issue entering the app and the first option is potentially a lot of work that it might not be worth fixing.

**Comment by TKDickson** [comment]
@Sparowhawk When I wrote this up, it was all examples of when display zoom was on before entering/logging in. It does seem possible/likely that real users might change things after login as well, @brea11y or @lstraghalis any thoughts on that?

**Comment by bischoffa** [comment]
@Sparowhawk thanks for bringing up that potential risk. Could you discuss with Binny to get his thoughts as well?

**Comment by TKDickson** [comment]
Yes, please schedule something. Also include @brea11y!

**Comment by brea11y** [comment]
Yes, please! I'd love to possibly talk through how this may / may not compare to the issue that I did the sprint zero on around [Display Zoom on Android](https://docs.google.com/document/d/1zJ1efdJNzZx9KutF0i8yC0KnXk4rV8E2JrlR8Xwqar0/edit?usp=sharing). It sounds like a very similar issue.

**Comment by Sparowhawk** [comment]
@bischoffa @dumathane @brea11y @TKDickson Do we have something on the calendar yet?

**Comment by bischoffa** [comment]
Not to my knowledge, I think Binny talked about scheduling something in a past DSU

**Comment by TKDickson** [comment]
At the meeting, decided that it wasn't worth the additional risk to try to support this edge case. Going to establish guidelines around this via work in #7183
