### ISSUE TITLE
Custom Tabs Login Update for Android Platform

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5118]
There is currently a bug in the way Android handles Google SSO Login. Android recently added functionality to their WebView that can be used to avoid showing an error in this case. We should update our app to use this new functionality.

Sprint 0: https://docs.google.com/document/d/1bi0vDgkd3W0PW9nse5unmb_GOe4xVFuqPhJS_T8OOH0/edit#heading=h.91nw9c7vgyg2

**Comment by StacyB2023** [comment]
Adding the following slack thread as a roll back of this epic may be done in the 2.9.0 Release: https://adhoc.slack.com/archives/C02N65QRRB7/p1691410981552169

An increase in login errors were found for android were found hence the reason for the roll back. A comment will be added to this ticket when the 2.9.0 roll back is official:


**Eng Summary:**

To summarize:
"We updated custom tabs in Android. SIS using JavaScript to execute a redirect in the authentication process. “Older versions of chrome on android do not allow for deep links to be launched using JavaScript. They require a user interaction or a 302 redirect in order to launch a URI.” - Narin
We need SIS to update the redirect (so it doesn’t use JavaScript), but that’s unlikely to happen before our next release. Narin has opened a rollback PR into the release branch (let’s make sure it gets into develop as well), but staging was down and he couldn’t test it.
That’s where we are, but the thread has all the info. We might need some quick testing and coordination to get it into the 2.9 release. "

**Comment by StacyB2023** [comment]
Moved Story #6130 to the Eng Tech Debt epic to be evaluated/prioritized later. Closing this epic as the applicable stories above completed with 2.8.0 release for audit trail purposes.

**Comment by StacyB2023** [comment]
10/11/23- Updated Epic with new template. Added comment under decision log for the following decision made 10/10/23:



There is currently a bug in the way Android handles Google SSO Login. Android recently added functionality to their WebView that can be used to avoid showing an error in this case. We should update our app to use this new functionality.

**VA Android login issue:
We have found a fix for the Firefox login issue (that also works for Chrome and Safari) but does not fix the Login issue for those that use Duck Duck Go as a browser. Do the VA POs want the team to complete the fix and release it for Firefox, Chrome and Safari, and open another ticket for the Duck Duck Go login issue and keep that as a Bug/WIP?
Rachel agreed that it was best to release the work that is ready to go (so, release the Firefox/Chrome/Safari fix) and to continue on the Duck Duck Go login fix under a separate ticket.**
