### ISSUE TITLE
BUG - sev-2 - All - Extra padding between screen header and content

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#5473]
## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

When looking at the different screen types (Category, Feature, Subtask, Full Panel), there's a different amount of space below certain headers. For example, on the Direct Deposit screen (feature screen type), there appears to be ~40px space below the header. But on the Payments category screen, there appears to be ~20px space below the header.

- Navigate to a category landing page
- Observe the padding between header and content
- Navigate to a different category landing page or a child page
- Observe inconsistencies in padding between header and content

## Desired behavior

According to a [Slack thread](https://adhoc.slack.com/archives/C01NC7PN4A0/p1681934699053039) with Lauren and Tim, there should always be 20px below the header. There appears to be extra space in the content area. Please check a wide range of feature/child type screens to be sure this is resolved globally.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High 

- 2 - High

## Screen shot(s) and additional information

![Payments.PNG](https://images.zenhubusercontent.com/63c8183fd2ad0e803513538d/6a5c0082-5305-4f2b-9c63-3226c8d05d3c)

![Direct deposit.PNG](https://images.zenhubusercontent.com/63c8183fd2ad0e803513538d/2490f38e-2394-4b8f-afd9-fb3b00740476)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@bischoffa @timwright12 apologies. The fixes themselves was fairly straightforward. It is a lot of screens though. So I have repointed it accordingly.

**Comment by Sparowhawk** [comment]
Fixed:
Claims > File Request
Prescriptions > Request Refill > Refill Request Summary Header
Prescriptions > Prescription Details > Extra padding between details and start of the details info/details and request refill button (if applicable)
Military Info
Notifications
Prescription > Prescription Tracking (Check type)
Home/Mobile/Work Phone/Email Address

Not fixed may need a additional change:
Prescriptions > Header when on Pending or Tracking tabs(this is due to tabbar being a specific height of 54(likely for bottom tab bar across the app))

Not fixed doesn't need changes:
Messages > Start New Message(the spacing is correct, it just looks off due to the border from Form Wrapper)
Messages > Reply(the spacing is correct, it just looks off due to the border from Form Wrapper)
Claims > Select files(the spacing is correct, it just looks off due to the border from TextArea component)
Claims > Select Photos(the spacing is correct, it just looks off due to the border from TextArea component)

I checked these pages and there isn't anything I can change without having to do one offs in one direction or another for each screen:
There also seems to be just an added pixel or two of padding on some pages where it a heading and then the content is text. Don't know if can be fixed though. For example Personal Info, Contact Info, etc

**Comment by Sparowhawk** [comment]
@jessicawoodin @rbontrager Yeah the issue primarily is that the button disappears on those tabs. The main issue outside of this is this tabbar is used for every tab bar in the app so removing it actually would be a decent amount of work to make sure it doesn't affect other screens.

**Comment by Sparowhawk** [comment]
I would estimate the amount of work to make that change would probably be a 3 to make sure nothing else is adversely affected

**Comment by jessicawoodin** [comment]
Oh, that's interesting. So even though the tabs are only used in prescriptions, any changes would impact other tab bars (including the bottom tab bar on every screen. That's definitely not ideal. If that's the case, I'd say we should leave it as is.

**Comment by Sparowhawk** [comment]
That is correct. Ok then this is good to go @rbontrager

**Comment by kidlaurenpeace** [comment]
Reopened to **address spacing discrepancies in all our Large Panel screens**. See a few examples on this [Slack thread](https://adhoc.slack.com/archives/C01NC7PN4A0/p1693577440999939). 

Spacing guidance can be found in [VA Mobile Shipped Files](https://www.figma.com/file/p0vlRz38TKIOwWDfI2bGc7/%F0%9F%9A%A2-Benefits-2.0---Shipped---VA-Mobile?type=design&node-id=1427-33523&mode=design&t=qVRPYSclDvdGJ13v-4) (Figma mockup).
