### ISSUE TITLE
CU - Ensure API Error statuses/objects are logged to firebase

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#5626]
## Proposed Change

We need to ensure our `logNonFatalErrorToFirebase` will actually log an api error object to firebase for our review.

## Why Should We Prioritize?

This will help us prioritize different api errors we are not prepared to respond with.

## Coding Time Estimation

3
	
## Checklist

- [x] Add the front-end label tag
- [ ] Attach to the Frontend epic for engineering initiatives

**Comment by bischoffa** [comment]
@timwright12 do you anticipate any major dependency work in Q4?

**Comment by bischoffa** [comment]
@timwright12 moving this to icebox as I did not see any major dependency work planned for Q4 and this has been blocked for over 3 months now.

**Comment by alexandec** [comment]
Related to this, I added an analytics event to the `logNonFatalErrorToFirebase` function which records all non-fatal errors along with error status, endpoint, and additional info. So even though Firebase itself is unchanged, we are accumulating a lot of useful error info. Putting the info into analytics also means we have much more flexible error reporting options. This ticket is still useful but it's less important due to the analytics error reporting.

**Comment by timwright12** [comment]
Is this still blocked? It looks like https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4145 was closed out

**Comment by alexandec** [comment]
@timwright12 I think Global can revisit this ticket, yep

**Comment by TKDickson** [comment]
Able to build, log in, and edit some contact info (just as a sample 'editing info' interaction) on iOS and Android. Unable to test the analytics portion of this; approved to merge.
