### ISSUE TITLE
Implement Deep Linking for Secure Messages 

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#6342]
## Description
Deep links are a type of link that send users directly to an app instead of a website or a store. They are used to send users straight to specific in-app locations, saving users the time and energy locating a particular page themselves – significantly improving the user experience.

As part of this story we want to Implement Deep Linking for **SECURE MESSAGES (MVP)** utilizing a custom URL via **EXISTING** push notification in the Mobile app.

**User Story**

**As a mobile app user, I want to be able to receive a push notification that will securely take me to my individual message within the mobile inbox. This will save me time in the navigation app flow and get me to my desired location faster.**

**This Story Includes:**

- **Back Navigation**: As a mobile app user, after i have navigated my inbox (via the deep link secure message), I would like to exit and be taken back to right place within the app.

Ex: User selects "health" back arrow- User should be taken to the "health" screen (not home screen as it is today

- **API Call Fail**: As a mobile user, when i log into the app, an i am unable to sign in (ex: wrong password), I receive a standard error message 

## Acceptance Criteria
  

-  [ ] Deep Link and navigate the user to the individual message (**Specific Message ID**). Ex: User receives a push notification and this will “deep link’ to the individual message within the mobile inbox.
**Note: Existing Push Notifications Only**
-  [ ] Back Navigation: As user exits the inbox, they will be taken back to correct Screen (**See Example above)**
-  [ ] API Call Fail: User will receive standard error message if a failure occurs at sign in. Existing Error Call Handling will apply.
-  [ ] Implementation should be done with future deep linking considerations. Ex: Adding Deep Linking for appts.

**Internal Spike for Reference:**[ HERE](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5667)

**Comment by theodur** [comment]
I wanted to provide an update from last week:

After working with the VA Notify team, I was able to have them update the notification template to include a link with the URL schema. Previously it was `msgUrl` which was an empty field. I also had them rename the field to `url` so that we can have a consistent field for future push notification to use as well. This will make it easier to branch out push notifications to other parts of the app. This also means future push notifications should have the `url` field in their payload following the URL schema specified in the React Navigation linking config in order for deep linking to be applicable to them.

The implementation work is complete, and the [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6305) is ready for review ✅ I will close this ticket since we have a [new ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6439) created for reviewing the implementation work.

Also wanted to note that a part of my development for this was using Detox to test push notifications locally, which was really helpful. I added the tests I used to the PR, which may help with [creating the test plan](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6371). I'll add a note in that ticket as well

**Comment by g-opzt** [comment]
> @theodur @g-opzt Calling out that AC 1 has changed to deep link the user not just to the inbox but to the individual message per ID. @g-opzt This may change your analytics ticket? I think you may have yours for deep linking just to the inbox itself.
> 
> cc: @dumathane

Yes, it does; thanks, Stacy. I will update that ticket today.

**Comment by htcollier** [comment]
[Updated the MVP flow diagram](https://www.figma.com/file/efonMkGyYE5Krx30gd0sG5/Deep-Linking---Discovery---VA-Mobile?type=whiteboard&node-id=33-562&t=yhRPzJ42I9IhAZ66-4) to reflect updated AC: 
<img width="951" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/45246038/1520b346-7c5c-43b0-bee8-52e040d34b60">

**Comment by StacyB2023** [comment]
@htcollier : Thanks Holly!!!
