### ISSUE TITLE
Enable analytics testing in staging

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6363]
![Screenshot 2023-07-20 at 4.39.22 PM.png](https://images.zenhubusercontent.com/6408a6976737d72a2677449e/f0f30729-74ce-42b8-92ac-da09449a70b2)

ACs:
- [ ] set analytics collection enable to true for staging environment
- [ ] Add a new parameter to all analytics events called `environment` with a value of "staging" if the event is logged in the staging environment; else null

**Comment by alexandec** [comment]
I think we should try to use Firebase's built-in environment and/or debugging features rather than adding a separate parameter for environment.

Note that someone previously documented an approach which is supposed to allow debugging/display of events not in production: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/App%20metrics/Firebase. I don't know if this still works or not but it could be a starting point.

**Comment by g-opzt** [comment]
Thanks @alexandec after touching base with QA I think we actually need to do a sprint 0 on this as enabling analytics testing will up QA resource demands. I've moved this back to "New Issues" and am spinning up the Sprint 0 on that.

**Comment by theodur** [comment]
Closing this since discovery was done, and https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8018 was created
