### ISSUE TITLE
FE: Create We Couldn't check you in Panel screen & implement logic to integrate with patch: check-in demographics

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6366]
## Description 
As a Veteran, I want to have some communication displayed if my check in request failed and what my next steps are to continue check in.

As part of this story we want to:   

- Create a screen for general error messaging 'We couldn't check you in'
- Integrate with [patch: /v0/appointments/check-in/demographics]( https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments~1check-in~1demographics/get)

See comment: for diagram of backend service workflow

## Acceptance Criteria
  

1. - [ ] Create general error screen [We couldn't check you in ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1680618865216/19982c43fee09740dedbf4ebaf4e7f12f4787b84?wid=0-1684960558535)

- Template: Full screen sub task
- Screen Title: We couldn't check you in
- Close is displayed on the top left
- Help icon top right
- Body copy:  We’re sorry. Something went wrong on our end. Check in with a staff member.

2. -  [ ] Verify when user has answered 'Yes' to all of the demographic screens presented(i.e contact info, emergency contact, or Next of Kin) that Patch /v0/appointments/check-in/demographics service call is made with the applicable update 
 

3.  Verify once patch call is made and successful that the app makes a Post /vo/appointments/check-in call.  
     - If Check in call is successful then display You're all checked in screen to the user (ticket #6005 )
     - If Check in call fails then display 'We couldn't check you in' screen 

4. Verify if patch update fails then display 'We couldn't check you in' screen

Note: If patch call fails, the user essentially be able to go through the check in process again as long as they are within the check in window and have not been checked in through other alternatives (i.e. at front desk, checked in using poster, etc)

5. Verify when selecting close the user is taken back to the appt details screen 

6.  Verify when selecting Help icon the user is directed to the check in appointment help screen

**Accessibility Requirements**
Standard:

1. Everything on the page should be read by the screen reader.

- If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the
component type needs to be announced by the screenreader. (Include name (title), role, value)
Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap,
or horizontal scroll.

2. Each touch target must be at minimum 44px by 44px

3. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.

4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.

5. For all lists with more than 1 option/result, screen reader should specify count of each option as it reads the option

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by jperk51** [comment]
The only part of the ACs I'm not sure about is what happens when the check-in call fails after patching demographics. There are two options really:
1. We can track that we attempted to patch and then /checkin still failed and show the "talk to staff" page
2. We just follow the same pattern for /checkin failures regardless of if we have attempted to patch recently (this is the simplest solution)

Additionally, there is a bit of a question around sequencing. I worked with checkin to figure out that only 27% of user who attempt to check in succeed without needed to have demographics info updated. This means we should just start with calling demographics first since that would mean most people experience 1 less API call for MVP. I'll update my flowchart to reflect that and share it on this ticket by EOD tomorrow. The flowchart will also reflect option 2 above. As part of our metrics we should pay attention to how long the API calls take and our own %s of how many people actually need to update demos in case the evidence points towards us swapping the order down the road.
