### ISSUE TITLE
Design System: Implement SegmentedControl Component into app

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6407]
Once the SegmentedControl component is built, update the app to pull in the new component.

Places in the app:
- Appeal Details
- Claim Details
- Claim History
- Appointments
- ~~Secure Messaging~~

AC:
- [x] use new component in each place listed above in the app
   - Secure Messaging split to #6647 
- [x] fix any broken unit tests
- [x] ensure the component still works as expected
   - [x] light/dark mode functions, etc.
   - [x] accessibility is in line with how components functioned previously
   - [x] Check if a11y hint works as intended when removing the same tag from the app translations (ensuring it's using the components package i18n)
- [x] ~~Update doc site documentation for SegmentedControl~~
   - Split to #6647

**Comment by DJUltraTom** [comment]
Giving 2 points for QA, 
QA will need to verify that the SegmentedControl Component does not affect function or appearance of the following areas. Existing test plans should suffice to ensure functionality:
- Appeal Details
- Claim Details
- Claim History
- Appointments
- Secure Messaging

**Comment by timwright12** [comment]
@rbontrager Tom added some notes on this one before he left

**Comment by TimRoe** [comment]
For documentation since Git/Zen-Hub being weird:
- [Mobile App PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6616)
- [Design system PR](https://github.com/department-of-veterans-affairs/va-mobile-temporary/pull/14)

**Comment by TimRoe** [comment]
> @TimRoe The android a11ylabels are incomplete (iOS is fine weirdly). For instance for upcoming appointments instead of 'Selected Upcoming, 1 of 2, tab, Review your upcoming appointments' you hear 'Selected, 1 of 2, tab, Review your upcoming appointments' with the word upcoming missing after selected.

Good catch! That would be a byproduct of cleaning up the testIdProps on the existing component which was being used to set accessibilityLabel without then setting accessibilityLabel myself (iOS automatically reads it without being told to).


@brea11y 
Related question to the above: with the way I reworked things, the screen reader would now read what is displayed instead of an internal identifier that doesn't necessarily match 1:1. For example, in demo mode in secure messaging there's 3 unread items so the screen reader as I have it would start:
- "Selected, Inbox 3, 1 of 2[...]" vs 
- Current in-app behavior of "Selected, Inbox, 1 of 2[...]"

My assumption is we'd want to retain the existing behavior, but wanted to confirm before reworking as such.

**Comment by brea11y** [comment]
That's correct. If possible, we would want to keep the existing behavior.

**Comment by TimRoe** [comment]
@rbontrager Changes made, ready for QA again.
