### ISSUE TITLE
Veteran Status ID- Analytics / Data

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6415]
**Purpose:**

- Involvement regarding kickoff 
- Involvement with what / how to measure success within the confines we have

**Notes**

- Functionality is limited - tag a section and a card pops up
- No validation from 3rd parties that this is being used or work

**Comment by g-opzt** [comment]
Analytics plan written [here](https://docs.google.com/document/d/1ruPGVW1KzwcYAj2Q2Tgy8a5e1nWWrCKiw7I9gtSnFv8/edit#heading=h.973g6efl0nkr) to be reviewed with team tomorrow.

**Comment by g-opzt** [comment]
## Measurement possibilities
### Not measurable under any designs considered so far
**Failures due to inability to login**: the screen will only have direct navigation behind authentication so we won't know if users are trying to log in to use it or something else.

### With existing analytics approach/existing data sources
#### Measurable:

**Utilization rate: How many users attempt to open the screen**
  * We should not expect 100% of users on versions with the feature to open this screen due to:
    * Veterans who already use alternative forms of proof of service and won't pursue another form
    * Veterans who are uninterested in proof of service ever OR would only pursue proof of service in situations that will not accept this type of ID. 

**Proxy success rate: Percent of users able to load the screen**
  * Starts when the user clicks to open the screen
  * Ends when the screen loads their information

**Fails**
  * if the API call to load the information fails
  * lack of internet/data connection: we can add a parameter to identify events logged in an unconnected state
 
**User sentiment about the feature**
* Monitor mentions of feature in app reviews and Reddit conversations

#### Product use to make data informed decisions
* A utilization rate goal could be set, but **there would be no data from the app to inform product decisions to reach that goal** if it is not immediately met.
* A proxy success rate goal could be set but **it will be measuring the reliability of dependencies, not user success**. This data could inform work on APIs but not the app directly.
* Data around lack of internet/data connection could inform mobile app product decisions on a range of features.

### With new data-gathering design options
#### Measurable with Yes/No questions only
**Direct success rate**
* What percent of users are able to successfully prove their service via the screen

#### Product use to make data informed decisions
* Direct success rate would inform product considers if the information provided on the screen should be changed and, if it is, to **monitor impact of those changes on success.**
  * There would be no contextual data to inform the decision, but it could be paired with existing user sentiment data sources and/or research to determine product modifications 

### With addition of a “No” follow up question (not currently in designs)
* Contextualized utilization: What are the different use cases Veterans are trying to leverage the feature for and do they affect overall success rate?
  * In-person vs online use
  * Discount vs. other use cases
  * Cases where proof of service leads to benefits vs those where even if the proof is accepted there is no benefit provided (due to lack of policy, etc.)
  * Rejections due to third-parties not accepting it as valid proof vs. other rejections

#### Product use to make data informed decisions
* This data would give direct insight into what contributes to failures that could be influenced via product changes, user communications (i.e. making users aware of known proof of service situations that wont’ accept this ID), or public communication (i.e. increasing awareness of ID form).

**Comment by g-opzt** [comment]
@bischoffa See last comment for summary of what's measurable under the different possibilities. I also drew out what implications those measurements would have for product data-informed decisions. We can discuss and refine with the VSID group to align with the final presentation.
