### ISSUE TITLE
Create list of existing API services in vets-api

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6453]
AC:
- [ ] Record a table of existing services in vets-api that we are NOT integrated with yet
- [ ] In the table include service name/location :: upstream API docs if possible :: purpose of the upstream API
- [ ] Recommendation for priority order for integration

**Comment by jperk51** [comment]
Timebox this at a 5

**Comment by kpethtel** [comment]
h1. Services as of 8/18/23

# app/services/bgs

all services in this folder use. BGS::Services. The latter is from a custom ruby gem so its functionality requires a bit more effort to seek out.

## app/services/bgs/people/service.rb
- find_person_by_participant_id

## app/services/bgs/awards_service.rb
- get_awards

## app/services/bgs/dependency_verification_service.rb
- read_diaries

## app/services/bgs/dependent_service.rb
- get_dependents
- submit_686c_form

## app/services/bgs/payment_service.rb
- payment_history: require's a user's file number.

## app/services/bgs/uploaded_document_service.rb
- get_documents

## app/services/form1010cg/service.rb
- a bit unclear, seems to be about processing a form1010cg. Uses MPI::Service and EMIS::VeteranStatusService.

## app/services/evss_claim_service.rb
I think this is a second class service that uses other services.
- all
- update_from_remote
- request_decision
- upload_document

## app/services/mhv_logging_service.rb
I think this is a second class service that uses other services.
- login
- logout

## app/uploaders
- contains a variety of uploaders, including evss document uploader and lighthouse document uploader.

## lib/apps/client.rb
this is not specific to user. not sure what it is
- get_all
- get_app
- get_scopes

## lib/bb/client.rb
- get_extract_status: PHR (Personal Health Record) refresh
- get_eligible_data_classes: Build the checkboxes for the form used to make a generate report request
- post_generate: generates report: Trigger a BB report generation
- get_download_report: Get a health record report. Because of potentially large payload size the content must be streamed.
- post_opt_in: Opt user in to VHIE sharing.
- post_opt_out: Opt user out of VHIE sharing.
- get_status: Get current status of user's VHIE sharing.

## lib/bgs/service.rb
uses BGS gem
- create_proc: not sure what a proc is in this case. doesn't appear to be about ruby procs
- find_rating_data
- create_proc_form
- update_proc
- create_participant
- create_person
- create_address
- create_phone
- create_child_school
- create_child_student
- create_relationship
- find_benefit_claim_type_increment
- vnp_create_benefit_claim
- vnp_benefit_claim_update
- update_manual_proc
- insert_benefit_claim
- get_ch33_dd_eft_info
- find_bank_name_by_routng_trnsit_nbr
- find_ch33_dd_eft
- update_ch33_dd_eft
- get_regional_office_by_zip_code
- find_regional_offices
- create_note

## lib/bid/awards/service.rb
- get_awards_pension

## lib/bip_claims/service.rb
- lookup_veteran_from_mpi: lookup veteran from MPI. uses MPI service. this seems redundant as a service

## lib/caseflow/service.rb
- get_appeals: Returns caseflow data for a user by their SSN.
- get_legacy_appeals: Returns caseflow data for a user via their SSN or file_number passed as headers
- get_contestable_issues: Returns contestable issues for a veteran.
- create_higher_level_review: Create a HLR in Caseflow.
- healthcheck: Pings the Caseflow health check endpoint.

## lib/central_mail/service.rb
- upload
- status

## lib/chip/service.rb
- get_demographics: Get the auth demographics data from CHIP
- update_demographics: Post the demographics confirmation data to CHIP
- get_token: Get the auth token from CHIP
- post_patient_check_in: Post the check-in status to CHIP

## lib/claim_letters/claim_letter_downloader.rb
uses VBMS::Client, so maybe not a first class service
- get_letters
- get_letter

## lib/debt_management_center/sharepoint/request.rb
- upload: Upload a PDF file of 5655 form to VHA SharePoint
- set_sharepoint_access_token: Set the access token for SharePoint authentication from Microsoft Access Control
- upload_pdf: Upload PDF document to SharePoint site
- get_pdf_list_item_id: Get the ID of the uploaded document's list item
- update_list_item_fields: Populate data columns with properties needed by VHA

## lib/debt_management_center/vbs/request.rb
- post: Make a HTTP POST call to the VBS service in order to submit VHA FSR

## lib/debt_management_center/debt_letter_downloader.rb
- get_letter: by document id
- file_name: by document id
- list_letters: for user

## lib/debt_management_center/debts_service.rb
- get_debts
- get_debt_by_id
- veteran_has_dependent_debts

## lib/debt_management_center/financial_status_report_downloader.rb
- download_pdf

## lib/debt_management_center/financial_status_report_service.rb
- submit_financial_status_report: Submit a financial status report to the Debt Management Center
- get_pdf: Downloads a copy of a user's filled Financial Status Report (VA-5655)
- submit_combined_fsr
- create_vba_fsr
- create_vha_fsr
- submit_vba_fsr
- submit_vha_fsr

## lib/debt_management_center/payments_service.rb
uses BGS::PaymentService and BGS::People::Request from gem
- compensation_and_pension: Returns a list of BGS Payment Hashes filtered by :payment_type == 'Compensation & Pension - Recurring' and sorted by :payment_date, ascending.
- education: Returns a list of BGS Payment Hashes filtered by :payment_type == 'Post-9/11 GI Bill' and sorted by :payment_date, ascending.

## lib/debt_management_center/statement_identifier_service.rb
seems to use data from MPI and vet360
- derive_email_address
- vista_account_id

## lib/decision_review/service.rb
- create_higher_level_review: Create a Higher-Level Review
- create_notice_of_disagreement: Create a Notice of Disagreement
- get_higher_level_review: Retrieve a Higher-Level Review
- get_notice_of_disagreement: Retrieve a Notice of Disagreement
- get_higher_level_review_contestable_issues: Get Contestable Issues for a Higher-Level Review
- get_notice_of_disagreement_contestable_issues: Get Contestable Issues for a Notice of Disagreement
- get_notice_of_disagreement_upload_url: Get the url to upload supporting evidence for a Notice of Disagreement
- put_notice_of_disagreement_upload: Upload notice of disagreement
- get_notice_of_disagreement_upload: Returns all of the data associated with a specific Notice of Disagreement Evidence Submission.

## lib/decision_review/utilities/pdf_validation/service.rb
- validate_pdf_with_lighthouse

## lib/decision_review_v1/appeals/supplemental_claim_services.rb
- get_supplemental_claim
- create_supplemental_claim
- process_form4142_submission: Creates a new 4142(a) PDF, and sends to central mail
- get_supplemental_claim_contestable_issues
- get_supplemental_claim_upload_url
- put_supplemental_claim_upload
- get_supplemental_claim_upload
- queue_submit_evidence_uploads
- queue_form4142

## lib/decision_review_v1/service.rb
- create_higher_level_review
- get_higher_level_review
- get_higher_level_review_contestable_issues
- get_legacy_appeals
- create_notice_of_disagreement
- get_notice_of_disagreement
- get_notice_of_disagreement_contestable_issues
- get_notice_of_disagreement_upload_url
- put_notice_of_disagreement_upload
- get_notice_of_disagreement_upload

## lib/disability_compensation/providers/intent_to_file/evss_intent_to_file_provider.rb
Uses evss/intent_to_file/service
- get_intent_to_file
- create_intent_to_file

## lib/disability_compensation/providers/intent_to_file/lighthouse_intent_to_file_provider.rb
Uses lighthouse/benefits_claims/service
- get_intent_to_file
- create_intent_to_file

## lib/disability_compensation/providers/ppiu_direct_deposit/evss_ppiu_provider.rb
Uses evss/ppiu/service
- get_payment_information

## lib/disability_compensation/providers/ppiu_direct_deposit/lighthouse_ppiu_provider.rb
Uses lighthouse/direct_deposit/client
- get_payment_information

## lib/disability_compensation/providers/rated_disabilities/evss_rated_disabilities_provider.rb
Not first class. Uses EVSS::DisabilityCompensationForm::Service
- get_rated_disabilities

# lib/disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider.rb
not first class. Uses lighthouse/veteran_verification/service
- get_combined_disability_rating
- get_rated_disabilities
- get_data

## lib/efolder/service.rb
Not first class. Uses VBMS::Client.
- list_documents
- get_document

## lib/emis/military_information_service.rb
- get_deployment
- get_disabilities
- get_guard_reserve_service_periods
- get_military_service_eligibility_inf
- get_military_occupation
- get_military_service_episode
- get_retirement
- get_unit_information

## lib/emis/military_information_service_v2.rb
- get_deployment
- get_guard_reserve_service_periods
- get_military_service_episodes

## lib/emis/payment_service.rb
- get_combat_pay
- get_reserve_drill_days
- get_retirement_pay
- get_separation_pay

## lib/emis/payment_service_v2.rb
- get_pay_grade_history

## lib/emis/veteran_status_service.rb
- get_veteran_status

(I documented EVSS before realizing that it's being sunset)

## lib/evss/dependents/service.rb
- retrieve: Fetches user info from the retrieve endpoint
- clean_form: Cleans in-flight form using form hash.
- validate: Validates in-flight form using form hash.
- save: Saves in-flight form using form hash.
- submit: Submits 686 form with form ID

## lib/evss/gi_bill_status/service.rb
- get_gi_bill_status: Retreive the status of a GIBS claim for a user

## lib/evss/intent_to_file/service.rb
- get_intent_to_file: Returns all intents to file for a user
- get_active: Returns all active intents to file of a particular type
- create_intent_to_file: Creates a new intent to file

## lib/evss/letters/download_service.rb
- download_letter: Downloads letter for a user.

## lib/evss/letters/service.rb
- get_letters: Returns letters for a user.
- get_letter_beneficiary: Returns benefit and service information for a user.

## lib/evss/pciu/service.rb
- get_email_address: Returns a response object containing the user's email address and its effective date
- get_primary_phone: Returns a response object containing the user's primary phone number, extension, and country code
- get_alternate_phone: Returns a response object containing the user's alternate phone number, extension, and country code
- post_primary_phone: POST's the passed phone attributes to the EVSS::PCIU service. Returns a response object containing the user's primary phone number, extension, and country code
- post_alternate_phone: POST's the passed phone attributes to the EVSS::PCIU service. Returns a response object containing the user's alternate phone number, extension, and country code
- post_email_address: POST's the passed email attributes to the EVSS::PCIU service. Returns a response object containing the user's email and effective date.

## lib/evss/pciu_address/service.rb
- get_countries: A list of country names
- get_states: A list of state names
- get_address: Mailing address for a user
- update_address: The updated mailing address for a user

## lib/evss/ppiu/service.rb
- get_payment_information: GETs a user's payment information
- update_payment_information: POSTs a user's payment information to EVSS and updates their current information

## lib/evss/reference_data/service.rb
- get_countries: Creates an object containing an array of country names
- get_states: reates an object containing an array of state names
- get_separation_locations: seems to be for fetching intake sites

## lib/evss/vso_search/service.rb
- get_current_info: Returns current info for a user by their SSN

## lib/evss/claims_service.rb
- all_claims
- find_claim_by_id
- find_claim_with_docs_by_id: GETs a user's claim information with documents included
- request_decision

## lib/evss/common_service.rb
- get_current_info
- get_rating_info

## lib/evss/documents_service.rb
- upload
- get_claim_documents

## lib/facilities/drivetime_bands/client.rb
- get_drivetime_bands

## lib/facilities/access_satisfaction_client.rb
- download

## lib/facilities/access_wait_time_client.rb
- download

## lib/facilities/client.rb
- get_all_facilities: by facility type

## lib/facilities/metadata/client.rb
- get_metadata

## lib/form526_backup_submission/service.rb
- get_upload_location
- get_upload_docs
- upload_doc

## lib/forms/client.rb
- get_all: Get all forms with an optional query parameter "query" for wildcard filtering.

## lib/gi/client.rb
- get_institution_autocomplete_suggestions_v0
- get_institution_program_autocomplete_suggestions_v0
- get_calculator_constants_v0
- get_institution_details_v0
- get_institution_children_v0
- get_yellow_ribbon_programs_v0
- get_zipcode_rate_v0
- get_institution_autocomplete_suggestions_v1
- get_institution_program_autocomplete_suggestions_v1
- get_calculator_constants_v1
- get_institution_details_v1
- get_institution_children_v1
- get_yellow_ribbon_programs_v1
- get_zipcode_rate_v1

## lib/gi/search_client.rb
- get_institution_search_results_v0
- get_institution_program_search_results_v0
- get_institution_search_results_v1
- get_institution_program_search_results_v1

## lib/gibft/service.rb
- submit: inherits from salesforce services and seems to submit a salesforce form to the route /services/apexrest/educationcomplaint

## lib/hca/enrollment_eligibility/service.rb
- lookup_user

## lib/hca/service.rb
HCA stands for HealthCareApplication
- submit_form
- health_check

## lib/iam_ssoe_oauth/service.rb
- post_introspect: Validate a user's auth token and returns either valid active response with a set of user traits or raise's an unauthorized error if the response comes back as invalid.

## lib/ihub/appointments/service.rb
- appointments: Fetches a collection of veteran appointment data from iHub.

## lib/inherited_proofing/logingov/service.rb
- render_auth:  makes an auth call to Login.gov with an inherited_proofing_auth param. Login.gov will pass this param back for validation in their user attributes call

## lib/inherited_proofing/mhv/service.rb
- correlation_id_api_request
- verification_info_api_request

## lib/lgy/service.rb
- coe_status
- get_determination
- get_application
- put_application
- get_coe_file
- post_document
- get_coe_documents
- get_document

## lib/lighthouse/auth/client_credentials/service.rb
- get_token: Request an access token

## lib/lighthouse/benefits_claims/service.rb
- get_claims
- get_claim
- submit5103
- get_intent_to_file
- create_intent_to_file

## lib/lighthouse/benefits_documents/service.rb
- file_number
- queue_document_upload
- queue_multi_image_upload_document
- cleanup_after_upload

## lib/lighthouse/benefits_documents/worker_service.rb
- upload_document

## lib/lighthouse/benefits_reference_data/service.rb
- get_data: Hit a Benefits Reference Data End-point

## lib/lighthouse/charon/service.rb
- call: not sure what this does

## lib/lighthouse/direct_deposit/client.rb
- get_payment_info
- update_payment_info

## lib/lighthouse/facilities/client.rb
- get_by_id
- get_facilities: Request a list of facilities matching the params provided; params must be a hash of parameter objects that must include bbox, ids, or lat and long
- nearby: Request a list of nearby facilities based on calculated drive time bands; Returns only health facilities; Returns only facilities within a 90-minute drive time

## lib/lighthouse/letters_generator/service.rb
- get_letter
- get_eligible_letter_types
- get_benefit_information
- download_letter

## lib/lighthouse/veteran_verification/service.rb
- get_rated_disabilities

## lib/lighthouse/veterans_health/client.rb
- list_bp_observations
- list_conditions
- list_observations
- list_medication_requests

## lib/mail_automation/client.rb
- initiate_apcas_processing: seems to be for sending emails regarding form526 processing. The file name makes it seem much more generic than it is.

## lib/mdot/client.rb
- get_supplies: GETs medical supplies available for reorder for veteran.
- submit_order: POSTs to DLC endpoint to create a new order.

## lib/medical_records/client.rb
- get_patient_by_identifier
- get_vaccine
- list_vaccines
- get_allergy
- list_allergies
- get_clinical_note
- list_clinical_notes
- get_diagnostic_report
- list_labs_and_tests
- list_vitals
- get_condition
- list_conditions

## lib/mhv_ac/client.rb
- post_register
- post_upgrade
- get_states
- get_countries

## lib/mhv_logging/client.rb
- auditlogin: Communicate to MHV, for compliance purposes, that the user has signed in
- auditlogout: Communicate to MHV, for compliance purposes, that the user has signed out

## lib/mpi/service.rb
- add_person_proxy
- add_person_implicit_search
- find_profile_by_identifier
- find_profile_by_edipi
- find_profile_by_facility
- find_profile_by_attributes_with_orch_search
- find_profile_by_attributes
- update_profile

## lib/oidc/service.rb
Unclear what these do exactly.
- call_no_token: this makes the actual call
- metadata: uses call_no_token to fetch metadata
- oidc_jwks_keys: seems to fetch keys from metadata

## lib/okta/service.rb
- app: gets an app
- auth_server: gets an auth server
- auth_servers: gets list of auth servers
- get_server_scopes
- user: finds user by id
- user_search_by_icn
- grants: by user id
- delete_grant
- system_logs
- metadata

## lib/pagerduty/external_services/service.rb
- get_services: Calls PagerDuty's GET /services endpoint, and returns pre-serialized representation of the raw response.

## lib/pagerduty/maintenance_client.rb
- get_all: gets maintenance windows

## lib/pagerduty/maintenance_windows_uploader.rb
- upload_file: seems to be for caching maintenance window data on S3

## lib/preneeds/service.rb
- get_cemeteries: POST to retrieve military cemeteries
- receive_pre_need_application: POST to submit a {Preneeds::BurialForm}

## lib/rx/client.rb
- get_active_rxs: Get a list of active Prescriptions
- get_active_rxs_with_details: Get a list of active Prescriptions using new model PrescriptionDetails
- get_history_rxs:  Get a list of all Prescriptions
- get_all_rxs: Get a list of all Prescriptions using different api endpoint that returns additional data per rx compared to /gethistoryrx
- get_rx: Get a single Prescription
- get_rx_details: Get a single Prescription using different api endpoint that returns additional data compared to /gethistoryrx
- get_tracking_rx: Get tracking for a Prescription
- get_tracking_history_rx: Get a list of tracking history for a Prescription
- post_refill_rxs: Post a list of Prescription refills
- post_refill_rx: Post a Prescription refill
- get_preferences: Get Prescription preferences
- post_preferences: Set Prescription preferences

## lib/salesforce/service.rb
salesforce stuff. who knows.

## lib/search/service.rb
- results: GETs a list of search results from Search.gov web results API

## lib/search_click_tracking/service.rb
- track_click: POSTs click tracking query param data to search.gov

## lib/search_typeahead/service.rb
- suggestions: GETs suggestion data from search.gov

## lib/sign_in/idme/service.rb
## lib/sign_in/logingov/service.rb
Obviously this relates to the signin service. Not relevant.

## lib/simple_forms_api_submission/service.rb
- get_upload_location
- generate_tmp_metadata
- get_upload_docs
- upload_doc

## lib/simple_forms_api_submission/service.rb
- notify: seems to be a script for sending slack notifications. Handy.

## lib/sm/client.rb
- get_preferences_frequency_list: Fetch the list of available constant values for email frequency
- get_preferences: Fetch the current email settings, including address and frequency
- post_preferences: Set the email address and frequency for getting emails.
- get_signature: Fetch current message signature
- get_folders: Get a collection of Folders
- get_folder: Get a single Folder
- post_create_folder: Create a Folder
- post_rename_folder: Rename a Folder
- delete_folder: Delete a Folder
- get_folder_messages: Get a collection of Messages
- get_folder_threads: Get a collection of Threads
- post_search_folder: Run a search of messages in the given folder
- post_create_message_draft: Create and update a new message draft
- post_create_message_draft_reply: Create and update a new message draft reply
- get_categories: Get message categories
- get_message: Get a message
- get_message_history: Get a message thread old api
- get_messages_for_thread: Get a message thread
- post_create_message: Create a message
- post_create_message_with_attachment: Create a message with an attachment
- post_create_message_reply_with_attachment: Create a message reply with an attachment
- post_create_message_reply: Create a message reply
- post_move_message: Move a message to a given folder
- post_move_thread: Move a thread to a given folder
- delete_message: Delete a message
- get_attachment: Retrieve a message attachment
- get_triage_teams: Get a collection of triage team recipients

## lib/token_validation/v2/client.rb
- token_valid?: not relevant to us

## lib/va_profile/address_validation/service.rb
- address_suggestions: Get address suggestions and override key from the VA profile API

## Get address suggestions and override key from the VA profile API
- update_communication_permission
- get_communication_permissions
- get_communication_items

## lib/va_profile/contact_information/service.rb
- get_person: GET's a Person bio from the VAProfile API
- post_address: POSTs a new address to the VAProfile API
- put_address: PUTs an updated address to the VAProfile API
- get_address_transaction_status: GET's the status of an address transaction from the VAProfile api
- post_email: POSTs a new address to the VAProfile API
- put_email: PUTs an updated address to the VAProfile API
- get_email_transaction_status: GET's the status of an email transaction from the VAProfile api
- post_telephone: POSTs a new telephone to the VAProfile API
- put_telephone: PUTs an updated telephone to the VAProfile API
- get_telephone_transaction_status: GET's the status of a telephone transaction from the VAProfile api
- post_permission: POSTs a new permission to the VAProfile API
- put_permission: PUTs an updated permission to the VAProfile API
- get_permission_transaction_status: GET's the status of a permission transaction from the VAProfile api
- get_person_transaction_status: GET's the status of a person transaction from the VAProfile api. Does not validate the presence of a vet360_id before making the service call, as POSTing a person initializes a vet360_id.

## lib/va_profile/demographics/service.rb
- get_demographics: Returns a response object containing the user's preferred name, and gender-identity
- save_preferred_name: PUTs an updated preferred_name to the VAProfile API
- save_gender_identity: PUTs an updated gender_identity to the VAProfile API

## lib/va_profile/military_personnel/service.rb
- get_service_history: GET's a user's military service history from the VAProfile API

## lib/va_profile/person/service.rb
We already use this.
- init_vet360_id: Initializes a vet360_id for a user that does not have one. Can be used when a current user is present, or through a rake task when no user is present (through passing in their ICN). This is an asynchronous process for VAProfile, so it returns VAProfile transaction information.

## lib/vbs/requests/list_statements.rb
It's a bit hard to tell because of the way it's structured, but I believe this can be used to list some sort of statements.

## lib/vetext/service.rb
- register
- get_preferences
- set_preference
- send_notification

## lib/virtual_regional_office/client.rb
Not sure what this is about.
- classify_contention_by_diagnostic_code
- generate_summary
- download_summary

## lib/vre/service.rb
Unclear what the VRE service does.
- get_token
- send_to_vre

## modules/appeals_api/lib/appeals_api
Has some slack, email report scripts, and token validation script. Probably not relevant to us.

## modules/apps_api/lib/apps_api/notification_service.rb
Seems to be about OKTA. doesn't seem relevant.

## modules/check_in/app/services/travel_claim/client.rb
## modules/check_in/app/services/travel_claim/service.rb
- token: HTTP POST call to the VEIS Auth endpoint to get the access token
- submit_claim: HTTP POST call to the BTSSS ClaimIngest endpoint to submit the claim

## modules/check_in/app/services/v2/chip/client.rb
## modules/check_in/app/services/v2/chip/service.rb
- token: HTTP POST call to the CHIP API to get an access token
- check_in_appointment: HTTP POST call to the CHIP API to Check-in an appointment
- refresh_appointments: HTTP POST call to the CHIP API to refresh appointments
- pre_check_in: HTTP POST call to the CHIP API to confirm pre check-in
- set_precheckin_started: HTTP POST call to the CHIP API to set pre check-in started status. Any downstream error (non HTTP 200 response)
- confirm_demographics: HTTP POST call to the CHIP API to confirm demographics update
- refresh_precheckin: HTTP POST call to the CHIP API to refresh pre check-in data
- initiate_check_in: HTTP POST call to the CHIP API to initiate check-in
- delete: HTTP DELETE call to the CHIP API to delete check-in/pre check-in data

## modules/check_in/app/services/v2/lorota/client.rb
- token: POST request to LoROTA token endpoint to get an access token
- data: GET request to the data endpoint to get the data stored in LoROTA associated with the uuid

## modules/check_in/app/services/v2/lorota/service.rb
Uses client above but adds some additional processing
- token: Get the token from LoROTA by making a POST call. If the call is successful, the token is saved in Redis as well for subsequent session retrieval.
- check_in_data: Get the check-in data from LoROTA. To get the data, the token (which is required for LoROTA auth) is retrieved from Redis. If token is not present, an unauthorized message is returned.If the data has been retrieved previously, it makes a call to CHIP to refresh the data in LoROTA first, and then gets the updated data from LoROTA.

## modules/claims_api/app/uploaders/claims_api
contains various claims file uploaders

## modules/claims_api/lib/bd/bd.rb
- search: Search documents by claim and file number
- upload: Upload document of mapped claim

## modules/claims_api/lib/bgs_service/benefit_claim_service.rb
This is odd. It seems to get data from parsing XML, not from an API. Not sure what's going on here.
- find_bnft_claim

## modules/claims_api/lib/bgs_service/claim_management_service.rb
This is odd. It seems to get data from parsing XML, not from an API. Not sure what's going on here.
- find_claim_level_suspense

## modules/claims_api/lib/brd/brd.rb
- countries
- intake_sites
- disabilities

## modules/claims_api/lib/claims_api/vbms_uploader.rb
not a true service. It uses the VBMS::Client. I believe it's a gem.

## modules/claims_api/lib/evss_service/base.rb
- submit: seems to be for claims submission. Oddly, this was written very recently despite EVSS being on its way out.

## modules/claims_api/lib/pdf_generator_service/pdf_client.rb
- generate_pdf: makes upstream POST to create PDFs.

## modules/covid_research/app/services/covid_research/volunteer/genisis_service.rb
- deliver_form

## modules/covid_vaccine/app/services/covid_vaccine/v0/enrollment_upload_service.rb
- upload

## modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb
- register

## modules/covid_vaccine/app/services/covid_vaccine/v0/vetext_service.rb
- put_vaccine_registry
- put_email_opt_out
- put_email_opt_in

## modules/dhp_connected_devices/lib/fitbit/client.rb
- get_token: HTTP POST call to the Fitbit API to exchange a string of the auth code for a user token
- auth_url_with_pkce: Generates a Fitbit auth URL with PKCE code challenge
- get_auth_code: Retrieves auth code from callback_params
- revoke_token: Revokes fitbit access token

## modules/facilities_api/app/services/facilities_api/v1/lighthouse/client.rb
- get_by_id: Request a single facility
- get_facilities: Request a list of facilities matching the params provided

## modules/facilities_api/app/services/facilities_api/v1/mobile_covid/client.rb
- direct_booking_eligibility_criteria_by_id

## modules/facilities_api/app/services/facilities_api/v1/ppms/client.rb
- facility_service_locator
- provider_locator
- pos_locator
- specialties

## modules/health_quest/app/services/health_quest/facilities/request.rb
- get: HTTP GET call to the Facilities API to retrieve a list of facilities by IDs

## modules/meb_api/lib/dgi/automation/service.rb
- get_claimant_info: connects to endpoint "claimType/#{type}/claimants"

## modules/meb_api/lib/dgi/claimant/service.rb
- get_claimant_info: same as above but connects to "claimType/#{type}/claimants/claimantId"

## modules/meb_api/lib/dgi/contact_info/service.rb
- check_for_duplicates

## modules/meb_api/lib/dgi/eligibility/service.rb
- get_eligibility

## modules/meb_api/lib/dgi/enrollment/service.rb
- get_enrollment
- submit_enrollment

## modules/meb_api/lib/dgi/forms/service/claimant_service.rb
- get_claimant_info: connects to endpoint "claimType/#{type}/claimants" (same as automation above)

## modules/meb_api/lib/dgi/forms/service/letter_service.rb
- get_claim_letter

## modules/meb_api/lib/dgi/forms/service/sponsor_service.rb
- post_sponsor

## modules/meb_api/lib/dgi/forms/service/submission_service.rb
- submit_claim

## modules/meb_api/lib/dgi/fry_dea/service.rb
- post_sponsor

## modules/meb_api/lib/dgi/letters/service.rb
- get_claim_letter

## modules/meb_api/lib/dgi/status/service.rb
- get_claim_status

## modules/meb_api/lib/dgi/submission/service.rb
- submit_claim

## modules/meb_api/lib/dgi/toe/service.rb
- get_toe_letter

## modules/meb_api/lib/dgi/toe/sponsors_service.rb
- post_sponsor

## modules/va_notify/lib/va_notify/service.rb
- send_email
- send_sms

## modules/vaos/app/services/vaos/v1/fhir_service.rb
- read
- search
- create
- update

## modules/vaos/app/services/vaos/v2/appointments_service.rb
- get_appointments
- get_appointment
- post_appointment
- update_appointment

## modules/vaos/app/services/vaos/v2/mobile_facility_service.rb
- get_clinic
- get_clinic_with_cache (uses above)
- get_clinics
- get_facilities
- get_facility
- get_facility_with_cache (uses above)
- get_scheduling_configurations

## modules/vaos/app/services/vaos/v2/mobile_ppms_service.rb
- get_provider
- get_provider_with_cache (uses above)

## modules/vaos/app/services/vaos/v2/patients_service.rb
- get_patient_appointment_metadata

## get_patient_appointment_metadata
- get_facility_clinics
- get_available_slots

## modules/vaos/app/services/vaos/cc_eligibility_service.rb
- get_eligibility

## modules/vaos/app/services/vaos/preferences_service.rb
- get_preferences
- put_preferences

## modules/vaos/app/services/vaos/user_service.rb
- session: creates session if none is cached
- update_session_token

**Comment by kpethtel** [comment]
The above is the output of this research. I created a list of (nearly) every outbound service in the vets-api. There were a few things I skipped because they were clearly irrelevant or redundant. Some of the above should probably be excluded because they are second class services (i.e., they use another service or gem to fetch the data) but it wasn't always clear what was a first vs. second class service. There were very likely some missed services as well.

I did not exclude services that we already use because I was focused on documenting, not figuring out what we use. I also did not link to api documentation or make any attempt to determine which of these we should try to use. I ran out of time.
