### ISSUE TITLE
Design System: Spike - Work on Strategy for Versioning of MDS and VA Mobile App

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6476]
We should have a clear strategy for how to handle versioning of the Design System itself.  FE and UX should work together on this.
Versioning Methodology: https://semver.org/ 

Things to take into account:
- aligning Figma versioning and component versioning
- Look at how others in the industry do it
- how would supporting older versions work?

AC:

- [x] document findings - in the ticket is fine
- [x] create stub stories to implement any changes needed

**Comment by bischoffa** [comment]
Carryover ticket from Sprint 81 into Sprint 82

**Comment by TimRoe** [comment]
The VA Mobile Libraries use [semantic versioning](https://semver.org/) at a per package level.

---
**Guidance in this section to be retired at version 1.0.0**
Despite technically being in production, the design system is still in early, rapidly iterative phases. With only the VA Health & Benefits app leveraging and close team contact, through at least Q1 2024 we plan to use a pre-launch versioning (major version 0) as follows:
- Version 0.1.0 will be a level set of the package highlighting it's in a workable state with baseline functionality that has been proven consumable by an outside project
	- For components:  Segmented Control ready to use
	- For tokens: Baseline set of color tokens available
	- For other packages: When the package has a core piece of functionality and is stably leveraged by an outside project
- Any/all breaking changes will be minor version increments that skip to the next "10" (e.g. 0.14.1->0.20.0) with tickets created for the VA Flagship Mobile Team providing specific guidance of necessary adjustments
- Aside from breaking changes, semver is updated according to long term guidance below

This policy will allow flexibility around anticipated growing pains that may entail more frequent breaking changes than more mature design systems. Once initial adoption challenges have been addressed and the packages have reached a degree of maturity in terms of content, version 1.0.0 will be published and follow the guidelines established below.

---

The guidance around versioning for the VA Mobile Libraries shall be as follows:
- Major
  - Breaking changes, large or small, that *may* require app-level changes to upgrade; examples:
	  - Non-backwards compatible update to an existing component property; e.g. renaming or restructuring how data is passed
	  - Removal of deprecated token(s)/component(s)/etc.
  - Underlying dependency update introducing incompatibility; e.g. new version of react-native that breaks compatibility to app-level version
  - In exceptional cases, may be incremented for a very significant package enhancement or totality of modest ones that comprise a bonafide "release" even without breaking changes
 - Minor
	 - Substantive functionality enhancements that are fully backward compatible, examples:
		 - New token(s)/component(s)/etc.
		 - Enhancing a component with a new variant
 - Patch
	 - Minor functionality enhancements that are fully backward compatible, examples:
		 - Adding a new property of minor impact
		 - Updating an existing component property with new values that have a minor impact
		 - Fixing internal bugs
 - Alpha
	 - Internal design system team testing build denoted by a `-alpha.#` appended to the semver
	 - Should not be used in production
 - Beta
	 - External team testing build denoted by a `-beta.#` appended to the semver
	 - Should not be used in production outside exceptional circumstances

The Figma Design Library will also follow this versioning guidance except only reflecting major/minor levels. Patch changes are likely to result in no visual changes or the design was correct while minor technical tweaks were made.



----
**Everything above this line intended to be added to repo-level documentation as is (with subsection set aside above to be removed when v1.0.0 is published). Everything below is just ticket-specific discussion.**

For AC:
> Look at how others in the industry do it

It seemed more a discussion about whether to version the repo/package as a whole or version individual components--we have largely proceeded already as versioning packages and doing per-component seems rather overbearing maintenance-wise so this research sticks with package-level versioning. Beyond that, other projects mostly don't seem to document versioning policies but seems a mix of following semver to pretty arbitrarily just doing sprint-based releases where every sprint is a minor bump and majors happening on a long span as needed. We could switch to that model in the future if it makes sense, but it does not seem to until a certain level of maturity.

For AC:
> how would supporting older versions work?

I am not sure we want to explicitly call this out in the guidance at the present time. I think this is a bridge to cross when we encounter a point where the most up to date version isn't just the obvious "use this version" which I suspect will be the case for the foreseeable future. I don't think we cross a bridge on this until we have 2 or more projects consuming our package and there is some underlying dependency breaking change (e.g. react-native) where one project wants to upgrade so we need a version for them and may also need to continue enhancing the prior version because another project is not ready to upgrade the dependency but does need some enhancement. It could be a long time until we encounter a situation that necessitates maintaining multiple versions in a meaningful way. 

Additionally: it sounds like deprecation cycles are heavily dependent on use--the smaller the footprint of projects using it, the more shorter timeframe one can move to not maintain an older version. As noted prior, with 1 project using we should be able to not worry about it; with 2-3 projects I think it heavily depends on the level of effort the change needs--if it's a one-line tweak, we are probably safe to move on without any old version support and expect them to address it to continue having the latest and greatest; if it's updating react-native, we should probably allow 3-6 months and potentially only maintain the older version in limited fashion (e.g. only updating with changes stakeholders want/need).

Lastly, a discussion point on:
> In exceptional cases, may be incremented for a very significant package enhancement or totality of modest ones that comprise a bonafide "release" even without breaking changes

It's very possible that we may need to make `major` level versions at times for nearly trivial changes. On the one hand, we can live with that and just set user expectations that just because breaking changes happened it doesn't necessarily mean anything interesting happened. On the other hand, we could establish a "version" level above major with named versions of something to that effect. For example, calling version 1.0.0 "Abrams" and, after a couple trivial major versions, having version 4.0.0 be release "Bradley" or something to that effect (my somewhat arbitrary example here using general names--as distinguished veterans--and following the alphabet). This would allow us to continue doing semver as appropriate while also delineating meaningful stages of "we've got something to show off!"

Thoughts on doing that or we good with some major versions not necessarily meaning anything of note a la "one component needed a property rename so it's a breaking change?"

**Comment by TimRoe** [comment]
To circle back on the discussion point:
- The team was tentatively, but not strongly, in favor of named versions
- We decided to bring to our product owner Ryan Thurlwell and [it was decided we'd move forward with using the major versions directly](https://dsva.slack.com/archives/C05HF9ULKJ4/p1698440429839629)

**Comment by TimRoe** [comment]
Instead of creating stub tickets, relevant parts were added as Def of Done criteria on:
- #6857 for the components package
- #6787 for the tokens package
