### ISSUE TITLE
BUG - Sev-3 - All - VoiceOver/Talkback - MessagesAppointments: A11y label tied to testID (causing some of our detox specific testIDs to be read)

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#6646]
## What happened?

More of an improvement ticket then a bug.  The a11y label is now tied with the testID (I think caused by ticket [6393](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6393)).  This is causing voiceOver/talkback to say the testID on top of the a11y hint.  We use the testID for detox so it needs to be removed from what is being said in voiceOver/talkback.

Locations:
Appointments: past dropdown
Messages: Start new message button, reply message button, to field, category field

## Specs:

- Device: All
- OS:
- User Account:
- Accessibility State: VoiceOver/Talkback

## Steps to Reproduce

1. Navigate to messages with voiceover/talkback on
2. Hover over the 'start new message' button.  Notice the testID is read
3. Hover over the 'reply' button. Notice the testID is read
4. Navigate to past appointments and tap the picker. Notice the testID is read 

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by DJUltraTom** [comment]
I am seeing the behavior mentioned above on android while tapping on "profile help" we get a "profi-profile help" read out loud.
On iOS we get the focus on profile help, then it "blips" away, and returns to "profile help" but it is not read out loud.
This behaviour occurs on all "profile help" screens

**Comment by DJUltraTom** [comment]
the above mentioned behavior is occurring on the "benefits > claims help" pages

**Comment by bischoffa** [comment]
When we scrub tickets can we add the Sev label to it as well. I added it for this one.

**Comment by Sparowhawk** [comment]
@rbontrager @DJUltraTom @bischoffa 

This is due to the following code that has been place for the past 3 years:

export const testIdProps = (id: string, disableAccessible?: boolean, integrationTestOnlyTestId?: string): AccessabilityProps => {
  const disableAccessibility = disableAccessible ? { accessible: false } : { accessible: undefined }

  const idToUse = IS_TEST && integrationTestOnlyTestId ? integrationTestOnlyTestId : id

  // setting both testID and  accessibilityLabel prevents elements from being found in the integration tests on iOS
  // testID is not used on android for the integration tests
  if (IS_TEST) {
    return { ...disableAccessibility, testID: idToUse }
  }

  return { ...disableAccessibility, testID: idToUse, accessibilityLabel: idToUse }
}

The issue is our old unit tests used to rely on testID to populate for the accessibilityLabel. We have been working on disconnecting the two but it still exists in several places. The two ways we can address this ticket is to either match up the testID to be the same as the accessibilityLabel or the regular text if there is none for that element or for us to complete disconnecting the two and fixing this code block. We should probably discuss this in FE Handoff to discuss how many points we think this might take.

**Comment by bischoffa** [comment]
@Sparowhawk thanks for the details and work!   
  
CC: @brea11y for awareness related to accessibility related items.

**Comment by Sparowhawk** [comment]
@rbontrager As discussed in Handoff if you could add the places where this is an issue on so we can work on each individual one. After that this will be ready to be worked. We repointed it after we discussed how we would fix this.

 @bischoffa  for LOS on priority and sprint planning

**Comment by bischoffa** [comment]
@rbontrager we can look to include this in our next sprint once we get your list of places where this is an issue. If we get this info by Monday EOD we can look to prioritize this for the next sprint

**Comment by bischoffa** [comment]
Blocking this ticket until we get feedback from @rbontrager on Sparowhawk's question.

**Comment by TKDickson** [comment]
changing from global to health, as this is for messages and appts

**Comment by alexandec** [comment]
Note for QA, need to ensure screen readers announce correctly for all uses of VAModalPicker, including:

- Past Appointments date range picker
- View Message move folder picker
- Compose Message/Edit Draft to picker
- Compose Message/Edit Draft category picker
- Payment History year picker
- Upload File type picker
- Upload/Add photos type picker
- Edit Address pickers (multiple)
- Edit Direct Deposit account type picker
- Developer Screen Sandbox pickers (multiple)

**Comment by rbontrager** [comment]
Verified that the screen reader correctly announce all use of VAModalPicker listed above.  Verified that this doesn't screw up any testIDs in the detox tests.  Approved by QA.
