### ISSUE TITLE
Bug - Sev-2 - Android login failing when default browser is Firefox

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6736]
Recent reports from users after the 2.11.0 release, which included our new custom tabs implementation:

> "I am verified on Login.gov but the app won't sign me in. When I click 'sign in' it goes to the login.gov page, I sign in, and verify through the two step process. But when it goes back to the app, it shows me the sign in screen again."

> "there was an update in the last few days. this update made the app to recycle to the login page after been authenticate buy "idme" which I didn't choose I chose myhealthevet credentials. Nevertheless it authenticated me through "idme" then sent me back to the VA login page."

> "Your latest update is broken. I can no longer login after updating the app today."

## Steps to replicate:

1. On Android device, change default browser to Firefox
2. Sign in the app with login.gov user vets.gov.user+12345@gmail.com
3. Login issue should present itself

We were able to confirm that, "it looks to happen only past the custom tabs re-implementation. Works fine in chrome and edge." [View the custom tabs re-implementation PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6613).

I was able to find some evidence of [Firefox issues with the launchMode](https://github.com/flutter/flutter/issues/56690), but the listed fix just exposed an older bug.

## Impact:

We're not able to get direct analytics for Android Firefox, but through SIS we estimated that 0.27% of users are potentially affected.

## Relevant links and background information

- [SIS thread about this issue](https://dsva.slack.com/archives/C03DY3FN7HQ/p1694694078283649)
- [Initial reporting of the issue](https://dsva.slack.com/archives/C018V2JCWRJ/p1694654535598999)
- [A potential fix that failed](https://dsva.slack.com/archives/C022SV53ASZ/p1694698934761459)

**Comment by bischoffa** [comment]
Discussed during SoS. PO said to prioritize this work just like any others when asked if they want it pulled in this sprint. 

Planning to include it next sprint.

**Comment by bischoffa** [comment]
@rbontrager has this ticket been scrubbed?

**Comment by timwright12** [comment]
@bischoffa Rachael and I talked about this async and set it as Sev-2, so it's ready for FE pointing

**Comment by bischoffa** [comment]
@timwright12 Per bug process the ticket needs to be label scrubbed and needs to be added to the bug epic as part of our standard process. Can we get those added.

**Comment by DJUltraTom** [comment]
Also failing when default is: 
DuckDuckGo and user is ID.me
Firefox Focus and user is ID me

Brave works fine
Opera works fine

**Comment by bischoffa** [comment]
@StacyB2023 looks like this is being treated as a bug ticket but I know its tied to the Custom tabs so I want to make sure you are kept in the log.

**Comment by bischoffa** [comment]
@timwright12 given no epic or scrubbed label added. I will add them this time but in the future we need to have bugs follow our standard process to get worked as expected.

**Comment by bischoffa** [comment]
FYI Rachel asked about this ticket in Sprint Planning informed it will be picked up. Given this was not tagged correctly I need to adjust bug tickets for next sprint to pull this in.

**Comment by timwright12** [comment]
This could be a red herring, but I looked into the rendering engines for Firefox and DuckDuckGo. They use different engines, and I didn't see anything really jumping out at me as far as a common theme, but DuckDuckGo seems to just use an Android WebView ([reference](https://www.reddit.com/r/duckduckgo/comments/12bazhj/what_browser_engine_does_duckduckgo_use/)) as its renderer.

Firebox mobile uses something called [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView) which "serves a similar purpose to Android's built-in WebView, but it has its own APIs and is not a drop in replacement."

So there might be a little overlap there to investigate with parallels between GeckoView and Android's WebView - also wondering if any other browsers use similar rendering.

**Comment by alexandec** [comment]
Results from logging in with vets.gov.user+12345@gmail.com via login.gov in my Andorid simulator:
- Chrome as default browser, android:launchMode="singleTask": App.tsx renders once, login successful
- Chrome as default browser, android:launchMode="singleTop": App.tsx renders once, login successful
- Firefox as default browser, android:launchMode="singleTask": App.tsx renders once, login successful
- Firefox as default browser, android:launchMode="singleTop": App.tsx renders twice, returned to login screen, error appears

Error text is:
```
Looks like you have configured linking in multiple places. This is likely an error since deep links should only be handled in one place to avoid conflicts. Make sure that:
- You don't have multiple NavigationContainers in the app each with 'linking' enabled
- Only a single instance of the root component is rendered
- You have set 'android:launchMode=singleTask' in the '<activity />' section of the 'AndroidManifest.xml' file to avoid launching multiple instances 
```

It appears that with Firefox as the default browser and android:launchMode="singleTop", the login is successful but a separate instance of the app is created. There's an instance of the app that the user doesn't see where the user is logged in successfully. But in the instance the user does see, it appears as if nothing happened. The linking error happens because App.tsx gets rendered once in one instance and again in the other instance. I'm not 100% sure but this appears to be what is happening.

The launchMode was changed in [this PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6613) to fix a different issue.

I will experiment further with different launchModes. Or we might need a different launchMode just for Firefox.

**Comment by timwright12** [comment]
Do we know the usage of DuckDuckGo to gauge impact? If it goes too long and the impact is low we might want to break off another PR/ticket for it

**Comment by alexandec** [comment]
The PR for this ticket is merged. It fixes the issue in Firefox and works fine in Opera, Chrome, and Edge on Android. We'll follow up on DuckDuckGo in the future since the fix doesn't cover that browser.

@timwright12 I don't think we know the usage stats for DuckDuckGo, but Greta could probably get us that info.

**Comment by TKDickson** [comment]
Samsung Internet (a whopping 3.61% aka 3rd most popular in [the US mobile browser share](https://gs.statcounter.com/browser-market-share/mobile/united-states-of-america)) was working for login on my Samsung Tablet, just to note that in here as well.

**Comment by bischoffa** [comment]
Carryover from Sprint 81 into Sprint 82

**Comment by timwright12** [comment]
@bischoffa I think this was merged into the release in Sprint 81. @alexandec Assuming there's no extra work beyond spinning up the DuckDuckGo ticket, can you close this out?

**Comment by alexandec** [comment]
@timwright12 yep, this was completed yesterday, closing it.
