### ISSUE TITLE
Bug - Sev 3 - UX Rd 2 - SM Login Issue - Error Message and Content Design - Bug 5986

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6738]
**Purpose:**
- Create a new alert message and content to better match the issue in ticket 5986 ; can do this by leveraging what MHV SM shows today in the web. 
- Veteran with premium account does not always get premium account access in mobile; thus need a message to tell them what to do when this happens

**Other Info:**
 We originally did this work in 6570 but Rachel on 9/14 indicated that we need new alert message / content specifically for this issue
- OG thought was to use the existing error message we had vs something new 
- Tied to [Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1694694600327349)

**Actions:**
- Create new error message that mirrors MHV Web's alert message for Mobile to create and use for the alert message for ticket 6571

**Comment by brea11y** [comment]
@mistymg – I have screens with the [existing content in Figma](https://www.figma.com/file/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?type=design&node-id=1212-12288&mode=design&t=Pg746ByVKBZaW4iu-4). If you need any adjustments to the design (those bullets can be a total pain to add/remove) to better accommodate your content, just let me know. I'm on standby.

**Comment by bischoffa** [comment]
![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/af24bb0e-860b-4b9a-91ab-a17969d14130)

**Comment by brea11y** [comment]
Since the screens to update the content for this work were put together [in Figma](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6738#:~:text=existing%20content%20in%20Figma) during the initial ticket, all UX work for this ticket is complete. I did chat with Misty when this ticket was assigned and she felt confident that no UX work would be needed to complete these updates. Any work needed to wrap up the content changes are being handled in Misty's ticket #6737. Closing this out for now, but am available if Misty needs any tweaks to those Figma screens to accommodate the content she writes.
