### ISSUE TITLE
Upgrade Mobile Datadog Dashboard

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6767]
Create a clone of vet-api's [dashboard](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/resources?env=eks-prod&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3Aall%2Csearch%3Amobile%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&start=1695654229162&end=1695913429162&paused=false) but prefilter for mobile. Carry over whatever portions of it you find most useful, but at a minimum make sure you bring over the "Resources" section at the bottom. This is extremely well done and show replace most, if not all, of our existing graphs. Additionally, due to how it's configured we will no longer need to worry about editing devops to ensure our endpoints are getting picked up/separated correctly. Also we want to update the existing monitors to query the same thing the resources board is instead of what we are doing now. You can find the monitors by searching for Jayson Perkins as the author. 

ACs:
- [ ] Create new dashboard based on vet-api's "Resources" widget
- [ ] Carry over whatever other metrics you think might be helpful
- [ ] Update existing monitors to query these metrics 
- [ ] Spend a day or two digging into datadog and make some tickets for improvements we might be able to make in the future

**Comment by kpethtel** [comment]
Created new dashboard [here](https://vagov.ddog-gov.com/dashboard/j6m-3ws-x4c/mobile-api-dashboard-20?overlay=changes&refresh_mode=sliding&from_ts=1696356300601&to_ts=1696961100601&live=true).

This dashboard has a nice per-endpoint error % graph and a list of recent mobile errors that mimics sentry functionality. The error % split view is also very valuable.

The page Jayson mentions above that we want to copy is not a dashboard. It's a service page. We are able to copy widgets from it and modify them for our purposes, but we don't currently have the ability to make a copy of it or to copy the resources list at the bottom of the page. That resources list is very valuable because it synthesizes all of the widgets into a per-endpoint view and allows for easy access to error logs for the endpoint. We can continue working with the platform team to reproduce that functionality on our own dashboard. 

In the meantime, my suggestions are:
- continue to work on fleshing out the new dashboard. 
- continue to work with platform to find a solution to the resources list constraint
- in the meantime, use a text box to add a link to the vets-api service page. That will give us easy access to it from our dashboard.
- investigate some of the highest CPU % resources from the list on the vets-api services page. Those are the most expensive endpoints and it would be valuable to understand why they're so expensive and whether we can make them more performant. This may reveal underlying issues in the interactions between the mobile app and vets-api or between the vets-api and upstream services.
