### ISSUE TITLE
SM Login Bug Issue - BE Discovery - Account Creation API 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6841]
Rachel shared a few updates related to the MHV Login Bug:

1. This bug is related to Account Creation API 
2. for this Account Creation API to be changed, new Terms of Use language need to be changed for va.gov. So the short term solution /error message is needed even more because this long term solution is going to take awhile

She indicated that Patrick may know something about the SM Login bug and long-term solution. This needs to be investigated: 

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/account-creation-notes.md

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGZhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--989bdd84311eb03a378a06ffd81fff60b997b23b/image.png)

**Comment by jperk51** [comment]
@rachelhanster Can you help me understand what kind of guidance you're looking for here? 

Based on what Patrick said, it seems like in the past MHV already started creating an API like what we would need in order to get accounts upgraded appropriately. Ultimately this would be between MHV and SIS since it has to do with user login data/account creation. MHV would need to boot the API back up then make sure it works and meets the current business logic they expect for this situation then SIS would need to add it as part of the sign in process. If SIS were to do that it would automatically upgrade accounts for both mobile and web regardless of where they logged in

**Comment by rachelhanster** [comment]
@jperk51 no guidance needed. I'm sharing context, that this problem with mobile is shared by web and mobile.

**Comment by jperk51** [comment]
@rachelhanster @bischoffa any qualms with me closing this ticket? 

I chatted with their BE lead a bit and they said they didn't see any issue with exposing this API, but next steps would be working with their PO to get it prioritized.

**Comment by bischoffa** [comment]
@jperk51 I am good with closing this discovery ticket. I will have another ticket created as a placeholder for when MHV SM and SIS decide to prioritize and make the changes. I know we aren't expecting any changes but want the placeholder to keep awareness and possibly for any testing needs we want to do to validate it works as expected.

**Comment by bischoffa** [comment]
Ticket for this is [6725](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6725)
