### ISSUE TITLE
Add new analytic event: Sign out

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6964]
- [ ] `vama_sign_out_click ` captures when a user clicks "Sign out" on the Settings screen

**Comment by Sparowhawk** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/6964?planning-poker) with Zenhub @alexandec @dumathane @narin @theodur @TimRoe

**Comment by Sparowhawk** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/6964?planning-poker) with Zenhub @Sparowhawk

**Comment by Sparowhawk** [comment]
Dylan Nienberg
  12:07 PM
When you get back on Monday I was wondering if we should combine Sharing the app and Sign out to a click one with a paramater of what is being clicked instead of having. multiple separate ones for individual buttons


Dylan Nienberg
  12:36 PM
We could also include the address change start click as well
So the thing would be
vama_app_click
thing clicked: string with the name you originally had
additional details: “mailing” or “home” in the instance of address change start, but the sharing the app and sign out would just b empty


Dylan Nienberg
  12:45 PM
I think we can change additional details and add extra parameters as needed that are optional


Greta Opzt
:nope2:  7:19 AM
One event for all clicks would be great. I do think it's a matter of figuring out if there are others that need additional parameters like the mailing address one, but I think we can just review it for future implementations. Thanks.

**Comment by Sparowhawk** [comment]
waiting on this one until after the CU ticket that removes the signout button component gets merged

**Comment by Sparowhawk** [comment]
@bischoffa the ticket I was referring to is already merged
