### ISSUE TITLE
Replace querystringify package with vanilla JS

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7010]
## Description

Based on the discovery from https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6913, the [querystringify](https://github.com/unshiftio/querystringify) package used in a few files in the repo can probably be replaced with the built-in [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) API. We are only using the `stringify` function.
## Acceptance criteria
- [ ] Replace instances of `querystringify` with the built-in `URLSearchParams` API

**Comment by theodur** [comment]
Note for QA:

The changes in the PR for this ticket impact authentication functionality and the directions link in appointments. Scenarios for both of those probably need to be tested. More specifically, for authentication, the functions that were updated are:
- `refreshAccessToken`
- `attemptIntializeAuthWithRefreshToken`
- `logout`
- `handleTokenCallbackUrl`
- `startWebLogin`

So the authentication flows that involve those functions may need to be tested

**Comment by TKDickson** [comment]
Test plan (and run)

- [ ] Get directions link in appointment with full address
- [ ] Get directions link in appointment without full address (may or may not be a thing)
- [ ] refreshAccessToken - start a workflow, put device down for ~30 min, attempt to finish workflow (ex: sending a message)
- [ ] attemptIntializeAuthWithRefreshToken: log in with biometrics
- [ ] handleTokenCallbackUrl: log in successfully with id.me
- [ ] handleTokenCallbackUrl: log in successfully with login.gov
- [ ] handleTokenCallbackUrl: log in successfully with DS Logon (if can find a valid user)
- [ ] _multiple of above_: attempt to log in with biometrics after it's been too long to log in with biometrics (not sure that I'll be able to mock this successfully, but will give it a whirl)
- [ ] _not sure but want to try_: log in successfully with IAM instead of SIS
- [ ] logout: log out successfully from Settings page
- [ ] logout: use Charles to block logout somehow, then attempt to log back in again (biometrics)
- [ ]  logout: use Charles to block logout somehow, then attempt to log back in again (UN & PW)
- [ ]  startWebLogin _ish_: start login, quit out of webview for login, then start login again and successfully complete

**Comment by TKDickson** [comment]
Found #7046 while testing, not caused by this change

**Comment by TKDickson** [comment]
TOU (terms of use) weirdness prevented me from testing any service providers other than id.me, and I didn't find any appointments that were missing location data AND had the 'get directions' button (probably a good thing). Otherwise tested the full plan above, and found the issues documented above. This is good to merge to develop.

**Comment by bischoffa** [comment]
@Sparowhawk please add a size to this ticket

**Comment by theodur** [comment]
@bischoffa I added an estimate for this even though it's closed
