### ISSUE TITLE
BUG - sev-3 - iOS - All "speech to text" is doubled, seemingly for our app only

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7264]
## What happened?

Using the iOS speech to text functionality, everything the user "type-says" is typed out, and then added to the text box AGAIN when they stop dictating. [Here's a video showing the duplication in our app, but not in the native mail app.](https://drive.google.com/file/d/1L4Hvsl4QnAGjtnKrPHmUdWTcCx9xUWZ5/view?usp=sharing) and yes, the video is showing it happening on the developer screen but I confirmed it's happening in places we care about as well (ex: preferred name field)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Only have the dictated text once, not forcing user to erase a whole bunch of stuff they don't want duplicated (or -- they don't notice it's duplicated and submit too much text, wasting time for someone else/making a mistake in what they're submitting)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by theodur** [comment]
@TKDickson I tried reproducing but wasn't able to. Since this ticket is old, I looked back to the version of React Native we were using at the time, and it was v0.71.7. This may have been a problem with the older version, because someone else also opened an [issue](https://github.com/facebook/react-native/issues/36031) in the `react-native` repo last year reporting this same issue, and they were on the same version that we were at the time. We're currently on v0.73.8 which seems to not have this issue. Can you confirm whether you're still seeing this?

**Comment by TKDickson** [comment]
@theodur yep it's fixed! Closing as.... probably can't reproduce I guess.
