### ISSUE TITLE
BUG - sev-2 - All - Availability Framework: Some screens not supporting use case 1

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7282]
## What happened?

When attempting to test use case 1 (DenyAccess), there are several screens where it's not working. When it doesn't work, it's showing up as a Use Case 3-styled banner with Use Case 2 functionality (yellow border, but no other content showing on the screen)

Screens that are **broken** for use case 1: 
- Veteran Status
- Veterans Crisis Line
- What to Know (before sharing gender info -- could be related to #7279?)
- RX Status Definition
- Start new message (from various end points - inbox, trash, sent)
- ReplyMessage
- FolderMessages 
- Developer Screen 
- Home Screen (kind of makes sense), 
- all of the category screens (payments, benefits, etc)
- Past Appointment Details
- Upcoming Appointment Details

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
This is different from #7403 -- all of the screens listed above are mishandling use case 1 in the same way (listed in the description), and 7403/claims history is mishandling UC1 in a unique way.

**Comment by theodur** [comment]
I updated the logic surrounding some of the screens in the list ([PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7430)). There are a few screens from that list that we may not need this for though:
- Developer screen (I don't think we'd ever need to apply case 1 to this)
- Home screen (Not sure whether this is needed, since after login, case 1 applied on the home screen would prevent users from accessing anywhere else in the app)
- Category screens (payments, benefits, health)(since these screens don't do anything other than display nav buttons, I don't think we'd need to block access to these screens, but rather block access to whatever feature we don't want users to access, e.g. Appointments, Prescriptions, etc)
- Veterans Crisis Line (I don't think we'd ever block access to this?)
- Veteran Status (same for this, I'm not sure that we'd need to block access to this, there's already logic to handling disabling navigating to this screen if military service history isn't available from the API)
- What to Know screen (this screen is just displaying information. I'd imagine if anything were to be blocked, it would be the gender identity screen, so the user wouldn't even be able to access this screen)

Just want to make sure we're intentional about where we're putting logic for blocking access. @TKDickson @dumathane What are your thoughts on the screens mentioned above?

**Comment by dumathane** [comment]
I agree with all of Theo's suggestions with veterans status and what to know being the exceptions. I think those are worth including use case 1ms for as the lift is minimal (the use chance is too, but not impossible)

**Comment by TKDickson** [comment]
Oh - and we'll need to document the pages that don't support it, in the ["weird ways AF works" draft file.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Framework_notes_DRAFT.md)

**Comment by TKDickson** [comment]
Good to merge to feature branch, and develop with the rest of AF.

**Comment by TKDickson** [comment]
Confirmed fix working in develop via spotcheck, closing.
