### ISSUE TITLE
Fix claim not found errors

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7519]
We've been seeing errors in the claims request decision endpoint when claim is not found in the database. 

Error log [here](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?env=eks-prod&graphType=flamegraph&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Aclaims%2CselectedResource%3A%28type%3Aresource%2CresourceID%3A8333ac3c792a8596%29%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=4507534500178944645&spanViewType=errors&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Aratio%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&timeHint=1702401730880&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&trace=AgAAAYxfDOlARPlAuQAAAAAAAAAYAAAAAEFZeGZEUHFnQUFCZkp1Z2R0c0QyRmdjYwAAACQAAAAAMDE4YzVmMGQtYzE2MC00YjcyLTk1ZmMtOWI4NTQyYTI0YWI4&traceID=2019806864130720079&view=spans&start=1702399198421&end=1702402798421&paused=true).

And in [sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/58015/?query=is%3Aunresolved+evss_id&statsPeriod=14d).

Acceptance criteria:
- attempt to determine why the claim is sometimes not found. The code was written on the assumption that the claim would always be in the database, probably because the claim has to be requested and written to the database before the user can look up the request decision. 
- determine how the code should behave. Should it return 404? Should it attempt to re-fetch the claim? 
- fix the issue
- update specs
- update docs if necessary

**Comment by charwo** [comment]
This may or may not be helpful, but: I was recently at the Regional Office in Philadelphia. I watched the contact center field a call from someone who called because the claim status showed that there was a decision, but when they looked there was no information about the decision.

The contact center agent said this happened a lot for dependency claims, because when a dependency form is processed, there is no "decision letter" they just process it. She believed that this appeared in our claim status tool as "decision made, here is a link" but that was confusing to people because there was no decision letter for this type of decision.

So potentially not all claims that make it to the "decided" state wind up with an actual decision letter.

I am sharing this because i was in the watch officer rotation and saw this fire, and wondered if it could be related, not because i'm sure this is what is going on.

**Comment by kpethtel** [comment]
@charwo that's good info. thanks for sharing. i'll link your comment to the other two open tickets that touch on this.

**Comment by charwo** [comment]
Can you share those tickets here so I can see them?

**Comment by kpethtel** [comment]
@charwo 
here's one: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7564
here's the other: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7234
