### ISSUE TITLE
Document Use Cases for Push Notifications 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7613]
AC:
- A list is created for all push notification use cases. This list includes the following:
   - Transactional use cases for features in the app with existing push notifications. Currently they are (Secure Message & Appointments)
   - Transactional use cases for features in the app with a existing, corresponding SMS
   - App-operations and promotional use cases 
 - List item attributes should initially include:
   - feature name
   - use case
   - push notification text
   - destination location
   - whether or not it can be turned off

**Comment by htcollier** [comment]
First pass at documenting use case for push based on criteria above & a quick review of VANotify and MyVA onsite notifications team github documentation: [VA mobile app - Push notifications](https://docs.google.com/spreadsheets/d/15II0OsOnKQrqr-5DQiCNa5MQq9qN2vhANVpU0yOzGf0/edit#gid=0 )

Need to follow up with VANotify team to confirm complete list of SMS messages (with content) that are being sent so that we can consider/adapt for mobile app. SMS messages in the doc are pulled from [VA SOP for Delivering SMS Messages v1.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20SOP%20for%20Delivering%20SMS%20Messages%20v1.0.pdf)

**Comment by htcollier** [comment]
Connected with VA Notify team to get the list of services and sms notification template names in production. Got access to VANotify's list of messages on https://notifications.va.gov

Confirmed with VANotify team:
Claims = Yes, BVA (Appeals)
Appointments = Yes, Reminders (VEText), eScreening questionnaire
Prescriptions = Yes, Shipping (VEText)
Secure Messages = No SMS, only email and push notifications
Vaccine records = No SMS
Payments = No SMS. DMC sends an email when a medical copay or other debt is incurred.  
Letters & docs = No SMS
