### ISSUE TITLE
CU- Investigate if rn-fetch-blob is a viable candidate to move to a native module or replace with a more maintained dependency

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7786]
It was found that rn-fetch-blob hasn't been supported in some time and it may be a candidate to replace with a native module or at the vary least a different dependency.

https://github.com/RonRadtke/react-native-blob-util/ is apparently a fork that is maintained that we could migrate to

**Comment by alexandec** [comment]
## Overview
We use [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) to download letters and store them in the local filesystem. rn-fetch-blob has been unsupported since 2019. We need to replace it with a supported package which receives security updates and keeps parity with React Native updates.

## Candidates
The best options to replace rn-fetch-blob are react-native-blob-util and react-native-fs.

[react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util/) is a fork of rn-fetch-blob. It is actively maintained with the most recent update in December 2023. Switching would be simple since it's a drop-in replacement. The only changes are to the package name:

```
const options: ReactNativeBlobUtilConfig = {
  fileCache: true,
  path: filePath,
  timeout: FETCH_TIMEOUT_MS,
}

const headers = {
  authorization: `Bearer ${getAccessToken()}`,
  'X-Key-Inflection': 'camel',
  'Authentication-Method': 'SIS',
}

const body = JSON.stringify(params)
const results = await ReactNativeBlobUtil.config(options).fetch(method, endpoint, headers, body)
const statusCode = results.respInfo.status
```

This package is the obvious choice for us because it's actively maintained and the switch is easy.

[react-native-fs](https://github.com/itinance/react-native-fs) is not a drop-in replacement for rn-fetch-blob but it's pretty simple to use:

```
RNFS.downloadFile({
  fromUrl: 'https://www.example.com/example.pdf',
  toFile: RNFS.DocumentDirectoryPath + '/example.pdf',
}).promise.then((response) => {
  console.log('File downloaded!', response);
}).catch((err) => {
  console.log('Download error:', err);
})
```

However, given that it was last updated in May 2022, it appears that it's no longer actively maintained. It's already falling behind based on the issues in the GH repo. I don't recommend we switch to a package that's already going stale.

## Decision
Let's switch from rn-fetch-blob to react-native-blob-util.

**Comment by alexandec** [comment]
Created [a PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8000) to switch from rn-fetch-blob to react-native-blob-util.

**Comment by DJUltraTom** [comment]
For QA, anywhere in the app where we download a file (claim letters, message attachments) we need to make sure the files are downloaded correctly. There shouldn't be any changes since the new package is a drop-in replacement. but just in case, it's good to test.

**Comment by DJUltraTom** [comment]
validated that claim decision letters, message attachments, and service letters can all be downloaded without an issue.
QA approves this change

**Comment by DJUltraTom** [comment]
verified claim letters, message attachments and service letters can be downloaded on last nights develop build
closing as "deployed"
