### ISSUE TITLE
UX: Make recommendation for "Start new message" button

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7805]
While performing the buttons and links audit in quarter 3, we ran across a couple of instances of the "start new message" button in the secure messaging area (main SM screen and within folders). Since this is a way to navigate to the screen where a new message can be composed and not an action to send the message, this should be a link and not a button.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

If possible, you may discuss with ENG whether it is feasible to simple switch out how this button is coded rather than changing the appearance of the "button" itself.

### Detailed information:
- [x] **Start new message**
     - **Location:** Health / Messages, Health / Messages / Drafts, Health / Messages / Empty folder, etc.
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** Compose
     - **What happens?** Redirects to the start new message subtask screen
     - **Recommended change:** Should be a link not a button. Icon should also be removed (this should already be in the works).

**Comment by wavelaurenrussell** [comment]
Recommendation: Have [Start new message button] read as a link

**Comment by alexandec** [comment]
@wavelaurenrussell @brea11y note that we are currently using the Button component for our "Start new message" buttons. The Button component does not allow the a11yrole to be changed -- only role="button" is allowed.

To implement the AC for this ticket, we'd have to switch the "Start new message" buttons from the Button component to using Pressable with role="link". Then we'd have to style the Pressable to make it look like the existing Button component. This is techincally feasible but it's not ideal because we'd end up with two types of "buttons" in the app. Both types would appear the same to the user but they would be styled and coded differently. Long term this type of approach often leads to problems because the two types get modified independently, leading to inconsistent appearance and functionality.

Alternatively we could approach the Design System team to see if they would add a parameter to the Button component allowing the role to be modified. This would be cleaner technically, but I'm not sure if they would be open to it.

**Comment by brea11y** [comment]
@wavelaurenrussell – This is one of those ["gray" areas](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Buttons%20and%20Links/) where it would fall into an action link on web. We had not put this documentation (or had those internal conversations) when this audit was done and the ticket was created. It's really up to us to make the call on using a button vs. a link here. Given all of the information that Chris just listed above, I'm good with leaving this as a button as long as you are.

**Comment by wavelaurenrussell** [comment]
> Alternatively we could approach the Design System team to see if they would add a parameter to the Button component allowing the role to be modified. This would be cleaner technically, but I'm not sure if they would be open to it.

I would prefer we investigate what it takes to add a11y role=link, in case this comes up again and to protect against audits @alexandec @brea11y. While I don't anticipate us having to change the role again if we hacked it, seems this would be a good thing for ds to bake into the component since it feels like a common situation that whatever designer/ally/eng may need to address in the future. Though as mentioned, I am not sure about the process to request ds to do things in this moment so I am tagging @ala-yna / @kellylein for guidance.
