### ISSUE TITLE
ENG: Update Profile App Headings

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7836]
The following updates need to be made in the profile area of the app. 
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [x] **Content:** [ veteran name ]
     - **Location:** Profile
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [ ] **Content:** Auth Tokens
     - **Location:** Profile / Settings / Developer Screen
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Authorized Services
     - **Location:** Profile / Settings / Developer Screen
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Environment Variables
     - **Location:** Profile / Settings / Developer Screen
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Encouraged Update and What's New Versions
     - **Location:** Profile / Settings / Developer Screen
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Push Notifications
     - **Location:** Profile / Settings / Developer Screen
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.

**Comment by theodur** [comment]
@brea11y Currently, the `Preferred name` and `Gender identity` titles on the Personal information screen aren't standalone text, they are grouped with the description in a single button and all the text in the button gets announced together when focused on. Just wanted to confirm, do you want the titles in the button to be announced as headings, even if after the header is announced, the screen reader will immediately read the subtext of the button? (e.g. "Preferred name, heading. Sharing your preferred name is optional.") The same applies to `Date of birth`, the only difference is it's not a clickable button.

Also, the veteran's name on the Profile screen is part of the nametag component, which all gets announced as one button. We may want to wait until HSP is merged into `develop` since in the HSP branch, the veteran's name is displayed differently as stand-alone text.

**Comment by brea11y** [comment]
@theodur – I agree. Let's circle back after HSP launches and I'll do a quick pass with the screen reader and determine what changes (if any) we'll need to make to the areas that you mentioned.

**Comment by theodur** [comment]
@brea11y That sounds good. FWIW it's only the Veteran's name on the profile screen that will be impacted by HSP. The rest of the checkboxes will still be the same after HSP is merged, so those could be worked on still. I already started draft PR that contains updates to the Developer screens. I'd just need to know if what I mentioned for the `Date of birth`, `Preferred name`, and `Gender identity` buttons is correct. But since we're gonna merge HSP soon, I'll just hold off until then.

**Comment by theodur** [comment]
@brea11y Since HSP is now merged into develop, this should be good to revisit whenever you have time

**Comment by brea11y** [comment]
Thank you, @theodur! I'll take a look tomorrow and let you know when I've revised the AC.

**Comment by brea11y** [comment]
@theodur – All of the AC should still be correct. On the main profile screen, we do want the Veteran's name to be a heading (especially now that it is outside of the previous nametag component). For the others in the personal information area (date of birth, etc.), if they are buttons (although, they should all be links, but this should be fixed in another ticket), they don't need to be headings. I believe I thought that these were all using a multi-touch card component instead of a button and/or link component. I've removed them from the AC.

**Comment by theodur** [comment]
Awesome, thanks for confirming @brea11y! The only changes needed here were on the developer screen with the updated AC. Just opened my PR for review

**Comment by TKDickson** [comment]
All items in ACs now being announced as headings

**Comment by TKDickson** [comment]
Doesn't require testing in develop; closing
