### ISSUE TITLE
Availability Framework - 20 March 2024 from 2-5am ET - Vets API Redis Update 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7848]
**Description:** 
As VAHB App, I want to implement the Availability Framework functionality on 3/20 at 2am ET for a couple hours to align with Vets-API Redis upgrade, so that VAHB know what to expect at this time 

**Notes:** 

- VA.gov traffic will show a maintenance page for ~1.5 hours at 2am ET on 3/20
- During this time users will not be allowed to sign in and users already signed in will experience an error 
-  Authentication will fail and they’ll return to the login screen
-  POs were originally notified on January 26th but this was postposed until 3/20
-  Maintenance windows do not support this change so AF selected as the solution
-  VAHB is in progress of making a AF policy and will take this situation into account
- [Slack thread with POs](https://dsva.slack.com/archives/C018V2JCWRJ/p1706287432647119)

**ACs:** 
AF Version 1 from 6pm ET Wednesday to until X am Thursday morning
- [x] Determine what component to use
- [x] Content creation 
- [x] Add alert to our pre login screen 
- [ ] Pre Production Testing 
- [ ] Turn on AF at 6pm ET Wednesday 3/19
- [ ] Turn off AF at Xam Thursday 3/20

**Comment by bischoffa** [comment]
Rachel (PO) confirmed only 1 message was needed.

**Comment by bischoffa** [comment]
Going to use this alert box on the pre-login screen 
<img width="356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c0f286a69dae76d556f6363ee4466cf4b5129fe/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Met with Binny, Misty and Therese to finalize ACs

**Comment by mistymg** [comment]
Unless we hear otherwise, we'll move forward with the following copy.

_**Header copy**_: Upcoming site maintenance

_**Body copy**_: We’ll be working on the mobile app on January 31, 2024 from 2:00 a.m. to 5:00 a.m. ET. During this time, you won’t be able to sign in. If you need help managing your VA benefits during this time, call us. We’re here 24/7.

_**Phone copy**_: 800-698-2411

_**TTY copy**_: TTY: 711

Screenshot of how it looks in yellow alert banner:

**Comment by TKDickson** [comment]
Did some preliminary looks at the content from the comment above in the app; on many phone styles with the default (non-zoomed) font, the banner on the prelogin screen will push the sign in button off of the page (just a note, nothing to be done about it). Chances of that increase for users with increased font/display zoom enabled.

Did a quick pass of the planned JSON in Slack as well. Overall risk for this feature (in terms of the AF banner *not* appearing when we want it to appear, or appearing in a broken fashion that we don't notice) is low, because it's showing up prelogin so Binny can confirm in PROD when he turns it on tonight.

**Comment by bischoffa** [comment]
Was working in production at 6pm ET. At 621pm ET VA sent a Slack messaging information Redis update is postponed (no new timeframe given). Rachel PO posted after hours to review the message which was lucky enough to be seen by Binny who removed it. 

Next steps is to wait for VA to tell Mobile updated timing and again coordinate work and effort to complete.

**Comment by bischoffa** [comment]
Moved to blocked until we get updated info from VA on when this needs to be released and removed

**Comment by mistymg** [comment]
When this does actually happen, I'd like to make a tinnnnyyy change to content :)

**Comment by bischoffa** [comment]
Not sure yet. Rachel is asking Mobile to monitor DSVA slack channels to find out. No updates as of yet. 
<img width="278" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/d56392c3-80d9-4101-9926-d636daa1e435">

**Comment by bischoffa** [comment]
No Slack updates from VA as of this morning

**Comment by bischoffa** [comment]
[No Slack ](https://dsva.slack.com/archives/C03R5SBELQM/p1706650201054529)update on Redis so no eta 

<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHN5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23604c5bcd64caa0c45d636610c93752077460fc/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
[Availability Framework process ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Process-%20Availability%20Framework.md)

**Comment by bischoffa** [comment]
Still no update or additional communication from VA on vfs-change-announcement

**Comment by mistymg** [comment]
I'm going to be out next week. If this happens while I'm out, here is the copy (small change from when I originally wrote it):


_**Header copy**_: Upcoming site maintenance

_**Body copy**_: We’ll be working on the mobile app on Month DD, YYYY from XX:00 a.m. to XX:00 a.m. ET. During this time, you won’t be able to sign in. If you need help managing your VA benefits, call us. We’re here 24/7.

_**Phone copy**_: 800-698-2411

_**TTY copy**_: TTY: 711

**Comment by ala-yna** [comment]
@dumathane latest I heard is this is scheduled for 3/20
