### ISSUE TITLE
Create logic for returning an error when attempting to send an SM without the associate triage group

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7862]
5 days prior to the transition of the 556 facility SM will be removing all triage groups associated with that facility. We need to stop messages from being sent that are missing the triage group on the message. 

AC:
- [ ] If a user tries to send a reply or compose a new message and send it to a triage group not on the users list we should stop it before sending the request to the MHV API and return an hardcoded error*
- [ ] updates tests 

* Check with the FE to see if a certain existing error code is preferred.

**Comment by jperk51** [comment]
Discussions still in progress about how we want to handle this.

**Comment by jperk51** [comment]
Meeting for early next week to solidify what's happening with SM

**Comment by jperk51** [comment]
Finally have a solution. Updating the ticket accordingly.

**Comment by kpethtel** [comment]
After some conversation with the MHV team and front end, I'm closing this as "no action needed". The MHV team confirmed that sending messages will not cause problems for their system and those messages will simply error. We could prevent that upstream call and handle the error ourselves by fetching the user's triage groups and confirming that the message's triage group is not present in the response, but it doesn't change the user's experience. If the mobile app receives a 400+ response code, the user experience is all the same. MHV will return a 400+ response. We could prevent the upstream call, but we'd have to make a different upstream call in order to do it, so there's really no advantage to changing our code and doing so would only add unnecessary complexity.
https://dsva.slack.com/archives/C0190MTGNUE/p1707339367424159
