### ISSUE TITLE
Update Large Nav Button Component for Category Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7936]
AC:
* Large nav button component for category screens is updated with designs in linked [Figma](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3328&mode=design&t=vJWw89ED2PwHi60F-4)

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
Created a copy, then [modified the existing Profile screen case](https://dsvavsp.testrail.io/index.php?/cases/view/59379) for this ticket. Will need to archive the old case after this merges into develop.

**Comment by TKDickson** [comment]
Should update this component, AND the deeplink button component, to set a max size for the icon: 

> Yes we should set a max size for the Activity buttons, can start with 24x24 (or whatever the chevron size is on the Veteran Status Card) and go from there.

**Comment by TKDickson** [comment]
Both iOS and Android (although I'm only showing Android, because I've seen it more regularly there) will fail to correctly preserve the loading UI spacing of 'title & skeleton loader' for the large nav button.

Here's a video showing how [Android struggles pretty much all the time/doesn't seem to be in reaction to my actions as a user](https://drive.google.com/file/d/1fpPuZQNpbi-DySjAFUaeGTX1kx_mE9H7/view?usp=sharing). 
Here's a video showing how I can [deliberately break the UI by switching between SR on and off ](https://drive.google.com/file/d/1fsd7WgzdA6qZrDdJzyzKyE0Ubm50nbWI/view?usp=sharing)(which is the only way I've found to break iOS).

^ on Theo's original branch with the skeleton loader + old button, I didn't run into this problem, despite running pretty much all of the same workflows/method of testing.

**Comment by TKDickson** [comment]
TestRail links for some Android detox tests I ran on this branch (less "I expect everything should pass" and more "I want to see exactly what is failing". Failed tests encompass both changes on this branch specifically, and all of the HSP2 branch generally)
[Home, profile and navigation](https://dsvavsp.testrail.io/index.php?/runs/view/5367&group_by=cases:section_id&group_order=asc)
[Veteran Status Card](https://dsvavsp.testrail.io/index.php?/runs/view/5368&group_by=cases:section_id&group_order=asc)

**Comment by TKDickson** [comment]
VQA uncovered the need for another ticket (to cascade the header style to the feature/child screens), that's ticket #8308. QA/VQA also agreed that we should try to better align some icons during text resizing, ticket #8309.

The rest of the work in this ticket, plus tickets #7383, #7598, and #243 (on the other repo) are complete. Approving merge to feature branch.

**Comment by TKDickson** [comment]
Merged to XL, closing.
