### ISSUE TITLE
BUG - SEV 2 - All - Review Message screens are displaying broken links inline with the text. 

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8096]
## What happened?
Review Messages are displaying links inline, instead of listing them as intended. 

## Specs
<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEdnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e5b188de1e0c9af6f29a71edabe5ede291af6e7/Andorid%20-%20SM.png" alt="Andorid - SM.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9nQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03597343bee5b72c19bf5d39bb965ff3a0d2bdb1/iOS%20-%20SM.PNG" alt="iOS - SM.PNG" />

## Steps to reproduce
In demo mode, navigate to a message detail screen and open a Message in this Conversation. You will see that some with listed links are displaying the reported behavior.

## Desired behavior
[Link to Mural wireframe](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678814753774/6419ffbf0434844d695912522dfdbc1c708345d7?wid=0-1685028022718&sender=uf97449a6574246b27b339084)

<img width="769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fd7b4430daf84390c0df3715821e1379cc30b43/SM%20-%20desired-%20link%20style.png" alt="SM - desired- link style.png" />

**Comment by Sparowhawk** [comment]
@wavelaurenrussell are you wanting this to use the new link component from the design library?
Should phone numbers and emails also be updated as well or just the urls?

**Comment by wavelaurenrussell** [comment]
@Sparowhawk yes we should use [the new link component](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/link--default) – especially pass the specific icons for these external links, and phone numbers. It doesn't appear that we have an email-specific icon, but I'd be open to making that external too, due to the behavior.

**Comment by Sparowhawk** [comment]
@wavelaurenrussell should the links be inline with the rest of the message like they were originally or should they appear below the rest of the text?

**Comment by wavelaurenrussell** [comment]
Was originally thinking below the message, but maybe its tougher than we think. Especially when they are inline with the message. Let me know thoughts.

**Comment by Sparowhawk** [comment]
Notes:

Try leaving message alone and extract the link and put it below the paragraph/text and send Lauren what that would look like

**Comment by rbontrager** [comment]
@brea11y Just double checking that this change works from an accessibility perspective.  The solution right now is to have the text of the message and then have any links/phone numbers that were in the message display below.  I've attached a screenshot. 
<img width="245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--416ca0116971a8aca7954ad8e1a47d02d8f62d25/Screenshot_20240501-124919.png" alt="Screenshot_20240501-124919.png" />

**Comment by brea11y** [comment]
Hey @rbontrager. So sorry for the delay in my response. I wanted to take some time and really think through the best possible option for this situation. Unfortunately, inline links have been an ongoing issue that we haven't quite been able to solve and implement into the app, but I think in this case, it is better to leave them vs. moving them down below the message.

I'd like to see if we can adjust the styling of them so that they are not bumping up above the the rest of the copy (my guess is that the line-heights differ between the copy and the links). They should also wrap like we see in the second (dark mode) screenshot in the ticket. 

The big accessibility issue with the inline links is that they would be "naked links", which is not very accessible, but would be better than them not linking at all within the message. Having the links / link copy in both places would force a screen reader user to hear them twice and / or force them to go search for the corresponding link at the bottom of the content. This could also cause issues for users with cognitive disabilities. The links wouldn't have icons (which isn't a big deal for accessibility) and would read out the full URL, which we can't stop either way.

If we can make those adjustments, I think we then have two options:
1. We include an alert (a yellow warning or a blue informational so we don't scare anyone) at the top of any message to or from a provider that includes links. If we choose this option, we could loop Misty in for copy, but I'd basically use the alert to explain that the links are presumed to be external links that will take them somewhere else (outside of the app).
2. The other option (and my preference) is to see if those external links will / could trigger the native "you're leaving the app" alert. If they can, we wouldn't need an alert above the message at all. For this option to work, the phone numbers would also need to trigger the action sheet that appears when you tap a phone number.

**Comment by wavelaurenrussell** [comment]
@Sparowhawk + @rbontrager: I caught up with @brea11y - can we revert this back to the original behavior where the links are interactive within the message, and launches the "You are leaving.." Alert/Dialog where appropriate? And investigate the line height/wrapping for Android, so that it looks like iOS.

**Comment by Sparowhawk** [comment]
Per discussion, revert changes, in the pr and look at android wrapping and line height issue on links to make it look better

**Comment by Sparowhawk** [comment]
I tried adding padding/margin and it made the problem in android worse. I also tried every way I can think of to wrap the urls and nothing worked.

Likely needs to wait until an inline link component from design-system team or a text view component.

**Comment by Sparowhawk** [comment]
This ticket was addressed when Chris updated to the other link component
