### ISSUE TITLE
Appts Endpoints: Discovery

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8212]
## Description 
Today, v0 of the appointments endpoint is being primarily utilized, specifically
- https://api.va.gov/mobile/v0/appointments/cancel/{cancelId} (and)
- https://api.va.gov/mobile/v0/appointments

As part of this discovery, we would like to investigate what new endpoints and information are available for the FE team to consume.
**Discovery Items**
1. Version Availability- Are there other API versions available? How accessible will they be to implement?
2. Is there a way to decipher appt type- Virtual, Phone vs. In person?
3. Web- what is web doing today?
4. [Booking notes ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7316)- can we get access to this field? 
5. How does the web team handle Calendar Appointments? Specifically, how do they handle appointment location for the four different types of virtual appointments? (see: [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5855))

## **Acceptance Criteria**
  

-  [ ] Research on Discovery Items listed above (Documented)
-  [ ] LOE for Implementation of a new endpoint
-  [ ] Note an Impediments, Possible Blockers for new endpoint implementation

**Comment by StacyB2023** [comment]
Other related ticket: (heath): https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8193

**Comment by ala-yna** [comment]
@StacyB2023, took a look at this ticket during refinement today and added a few updates. Thank you for taking this on, and let me know if you have any questions!

**Comment by ala-yna** [comment]
1. Our V0 feeds into Appointments V2. 
2. We could pull a list of all available upstream information. 
3. There are potential mismatches between what FE calls a given field and what we call it. 
4. Comments shows up in the mobile app as special instructions, where are booking notes?
5. For mobile frontend, booking notes = veteran feedback to provider
6. If there is information we are missing because Web is pulling info from a different endpoint, that's something we could look into once we know that

Action Items:
- BE to pull a list of available fields, to compare to a list of what we sent to the FE. 
- BE to set up a meeting to show give a demo of how to trace fields
- BE to investigate if we have access to booking notes
- FE to investigate what field booking notes is coming from for web
- FE to map what fields are mapping to what backend data (overall data audit)

**Comment by StacyB2023** [comment]
@ala-yna and Team- Great discussion today!

On the BE notations listed above.

1. **BE to pull a list of available fields, to compare to a list of what we sent to the FE**- Provided on the call but there may be more specifics the health team needs and can reach out.

2. **BE to set up a meeting to show give a demo of how to trace fields**- Yes. @jperk51 is happy to Demo this. Please note that field tracing involves several steps (in discussing with Jayson)  across various codes repositories and then possible contract to the upstream team (in this case: VAOS) to confirm items. Agree this will be great to see.

3. **BE to investigate if we have access to booking notes-** Discussed on the call. We are showing this field on the BE (access to the field). 3 Options are returned as to what "booking note" can possibley be. **_Web confirmation would still be needed to see what the exact usage applies to the team._**

Once confirmation is received (on booking note), Health team will need to determine How we want to display the filed on the current UI? BE can then work with health team to revamp fields to show the right spot **(Depending on the Overall Scope etc).**

cc: @wavelaurenrussell @mistymg @ala-yna @Sparowhawk @jperk51 @rbontrager 

Thanks!

**Comment by ala-yna** [comment]
Closing this ticket out - this work was associated with the appointments work done earlier this year.
