### ISSUE TITLE
Fixing React Query Downtime

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#8292]

**Comment by rbontrager** [comment]
Maintenance windows work but the change doesn't account for the user banner on the home screen/profile screen.  So if military info/disability rating is in maintenance its still showing the branch/military seal on the banner and isn't getting rid of the fields in maintenance in the veteran status panel. Moving back to in progress for now.

**Comment by rbontrager** [comment]
Talked with Binny and he says this will be fixed in home screen personalization and verified with [7967](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7967). 

I confirmed that all maintenance windows work with react query and that Dylan is adding the same logic to any new react query changes.
