### ISSUE TITLE
Investigate mobile usage of Direct Deposit, specifically C&P + EDU Forms

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8332]
I received the following message:

"We are finishing up the work for combining the two separate direct deposit forms (C&P and EDU) into a single form.  This means users will only manage one direct deposit account that applies to either C&P, EDU, or both.
When the form is displayed, the Profile section will inform users about which benefit type the direct deposit information is related to (C&P, EDU, or both). To determine the benefit type, Lighthouse has added an additional flag to the control information - isEduClaimAvailable.
So the basic logic is this...
if isCorpAvailable == true                # then DD info is for C&P benefits.
if isEduClaimAvailable == true            # then DD info is for EDU benefits.
if isCorpAvailable && isEduClaimAvailable # then DD info is for C&P and EDU benefits.
I know you mentioned that mobile doesn't have the EDU direct deposit feature, but the current mobile C&P form may need an update to better inform users about which benefit types the account is associated with.
If all goes well, we plan to deploy these change to production by Apr 20.
Let me know if you want to discuss this further."

We need to investigate if/how this affects us

**Comment by jperk51** [comment]
might be related to the migration I linked in the dependencies

**Comment by StacyB2023** [comment]
Adding this thread here for reference: https://dsva.slack.com/archives/C06JV0KHZNF/p1713211656845489 . This ticket covers the investigation

**Comment by aherzberg** [comment]
Just talked with Tom Harrison from the profile team and they are going to be displaying direct deposit information generically, without displaying if it's EDU or C&P. I suggest we do the same. Luckily our FE is already generic and does not mention C&P so the changes required from BE will be minimal. The only change that will be required if we do not need to pull in these new flags (since we wouldn't need to label if it's EDU or C&P on the FE) will be to update the confirmation email to be generic instead of referencing C&P as it does now. Tom has a PR out to do this https://github.com/department-of-veterans-affairs/vets-api/pull/16357. once that is merged, I'll change our controller to use the new email template.
