### ISSUE TITLE
 How to sign into the app in staging with MHV credentials

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8367]
## Description 
As a Mobile Testing, I want to document how to log into staging using MHV credentials, so that Mobile knows how to do it and can share it with those that need to know this. 

As part of this story we want to:   

- Document how to log into staging using MHV credentials
- Document any points of contacts if there are issues 

**Accessibility Requirements**
- None

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
Created a demo video (only accessible within Ad Hoc's google instance) and shared it on the VA mobile app internal slack channel.

Not posting on the doc site or github, because the video is not really appropriate for a public website (because of the tech needs involved, the workflow can only be done by Ad Hoc employees; posting it publically is just asking for someone who wants to do the workflow and can't, to stumble across it)

Closing.
