### ISSUE TITLE
Update the "We couldn't find a bank linked to this routing number..." Alert to Align with VADS Guidance

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8400]
To better align with the VADS Guidance [regarding slim alerts](https://design.va.gov/components/alert#examples---slim-alert---v1), we should update the copy within the alert to be descriptive copy (not bold) instead of the bold (heading) copy that we have currently.

**Comment by juancstlm-a6** [comment]
Should this be under the Design System as the Alert being referenced comes from the Design System?

**Comment by brea11y** [comment]
No, this is something that needs to be handled on the app side. The design system team only handles changes that need to be made to the component itself (i.e. a background color change). The app team handles anything related to implementation, content adjustments, etc.

**Comment by juancstlm-a6** [comment]
@brea11y Got it from the short description it made me think this was a component change rather than a implementation change.

I believe what we are looking for is to update the alert to something like the "After" screenshot?

There isn't, from what I could tell, a "Slim" version of the Alert on mobile and the "Slim" look is mimicked by omiting a header copy. This is still not a "Slim" version entirely as it the padding is a bit bigger than on the web but this is the closest we can get without altering the component itself and creating a proper "Slim" variant

| Before | After |
| --- | --- | 
| ![Image](https://github.com/user-attachments/assets/2092cb28-5455-4bb6-ad9c-90c029ac4052) | ![Image](https://github.com/user-attachments/assets/da0d4704-cd07-48b5-8a87-80cffc913953) |

**Comment by brea11y** [comment]
Absolutely! You got it! There are a lot of these tickets out there for these alerts that only have a single line of copy in them. Right now, in the app, if they only have a single line of copy, the copy is bold when it should be a regular font weight (like the after screenshot). This is what VADS is doing for their "slim alerts" and to better align with VADS, we should do the same. 

However, we also don't want to remove existing copy and force it into a slim alert style, so if you do come across one of these tickets and it would require you to remove existing copy, just let me know because it is likely that the copy has been updated since the tickets were created. It looks like this ticket might be one of them. When the ticket was created, this alert did not have the "We can't update your bank information" heading inside the alert. If that is what exists in the app today, you can disregard this update.

**Comment by juancstlm-a6** [comment]
Got it thanks. The current alert has both a `heading` and a `description` copy so based on your comments no change is needed here. We can probably close this ticket

**Comment by brea11y** [comment]
Sounds great! I'm closing it now! Thank you!
