### ISSUE TITLE
BUG - sev-2 - All - Pre-feature-screen calls on RQ-migrated features don't respect maintenance windows

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8432]
## What happened?

_I'm not sure what happened to my original writeup - ugh! - but writing it again_

We are currently calling the APIs for Rx, claims and appeals sometime during the "post login & home screen loading" sequence, even if a maintenance window is set for those features.

We are NOT making those calls for messages or appointments, so it appears to be tied to RQ migration. 

Dylan's initial thought is that it's a race condition, [see slack thread](https://adhoc.slack.com/archives/C02N65QRRB7/p1713539992267519).

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
@dumathane @Sparowhawk There are now 2 PRs associated with this ticket, and nothing in the ticket explaining what's going on. Add notes, and then QA can actually work it.

**Comment by TKDickson** [comment]
In a call about this ticket:
* This is now being fixed by @theodur  - PR 8481 - and not @Sparowhawk / PR 8433.
* Therefore this is now going to be tested by @TKDickson not @rbontrager 
* It involves a more fundamental change, notes will be added by Eng about what changed & where it changed
* RB was running into issues during initial testing where log out and log in worked, but initial install login and biometrics were broken (race conditions).

**Comment by theodur** [comment]
Things updated for this ticket:
- The logic that enables the following queries: `getAppointments`, `getAuthorizedServices`, `getClaimsAndAppeals`, `getDecisionLetters`, `getDisabilityRatings`, `getServiceHistory`, and `getPrescriptions`. The checks for downtime and authorized services were directly added to these queries to ensure they aren't called when they shouldn't be.
- Screens that were using at least one of the queries above and manually checking downtime or authorized services before enabling the query. These screens no longer enable/disable the queries based on checking downtime or authorized services, since that logic is now checked directly in these queries. The updated screens are: `Claim details`, `Claims history`, `Disability rating`, `Appointments`, `Prescriptions`, `Refill request`, `Military information`, `Profile`, the Sync screen, and the Home screen. Ideally, the functionality of these screens should be tested when the feature for the screen is down and/or when the user isn't authorized to access the related feature to make sure the screen handles that appropriately. (Note: The messaging shown on the screen may be wrong due to https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8447), but the user still shouldn't be able to access the feature on the screen.
- The logic for completing syncing the Sync screen was updated to include waiting for the downtime API call to finish.

**Comment by bischoffa** [comment]
Labels updated to reflect that Global took this ticket from Health.

**Comment by bischoffa** [comment]
@DJUltraTom Therese was wondering if someone in QA would have capacity to pick this up as she is limited again today. Can you look into this ticket today?

**Comment by DJUltraTom** [comment]
I'm looking at the API calls using charles proxy using an on-demand build and could use some clarification.
@theodur  how would you advise verifying the fix is in?
I'm assuming I would mock the maintenance windows and verify the api's for the features in the maintenance window are not being called?
(if this is the case everything aside from appeals and RX seem to be working, but this could be user error in my maintenance window json, I'll sync with you Thursday)

**Comment by DJUltraTom** [comment]
Synced with @theodur and @dumathane and eliminated the user error.
When a feature is in a maintenance window the API is no longer being called.
QA approves this

**Comment by DJUltraTom** [comment]
checked against the maintenance windows using the overnight QA build, and its working as expected!
marking ticket as closed
