### ISSUE TITLE
Lighthouse Direct Deposit: undefined 'delete' for nil

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8473]
https://vagov.ddog-gov.com/apm/error-tracking/issue/a80368e8-f4d2-11ee-ab20-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&refresh_mode=paused&view=spans&from_ts=1712976884686&to_ts=1713066884686&live=false

Work with lighthouse to figure out why `delete` is getting called on nil and help get the issue resolved

**Comment by kpethtel** [comment]
The underlying issue here is that the lighthouse service exception doesn't handle timeouts correctly. I fixed it specifically for direct deposit endpoints but was reluctant to fix it more broadly because it would impact several controllers outside of the mobile module. In addition to the work done in the linked PR, Tom Harrison opened [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83237) for a broader fix to the issue.
