### ISSUE TITLE
Update app colors to align with VADS/USWDS

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#8476]
In department-of-veterans-affairs/va-mobile-app#7371, we updated the primary colors to align with VADS/USWDS.

On January 8, [VADS will be updating their remaining colors to align with USWDS](https://dsva.slack.com/archives/C01DBGX4P45/p1704385447508359). We need to update our colors in the app. The design system color tokens will be updated in department-of-veterans-affairs/va-mobile-library#119.

**The mobile app team needs to update the HEX numbers in the following locations:**
- [ ] [this file in va-mobile-app](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/styles/themes/VAColors.ts) (front-end)
- [ ] [the design library files in Figma](https://www.figma.com/files/827597988283174959/project/60961499) (UX)

The color changes are outlined below.
<img width="398" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39a293b73e4770331456e0dcd47077dca45005af/colors.png" alt="colors.png" />

**Comment by brea11y** [comment]
@dumathane  – Just an update on this. I touched base with @jessicawoodin yesterday. She said that this ticket is older (prior to the design tokens work) and that she doesn't think we should just update the hex #. Instead, we should likely be referencing the design tokens, but that she wanted to double check with Narin. She is going to chat with Narin to see if this ticket needs to be updated so that we have all of the necessary information to groom it and then complete these updates.

**Comment by jessicawoodin** [comment]
This ticket will be addressed with #[7573](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7573), so I'm closing this out.
