### ISSUE TITLE
EVSSDisabilityCompensationForm Outage

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8490]
Investigate if there is a way to add EVSSDisabilityCompensationForms to maintenance windows

https://vagov.ddog-gov.com/apm/error-tracking/issue/c8ae83d0-832a-11ee-988e-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&refresh_mode=paused&view=spans&from_ts=1714406180154&to_ts=1714496180154&live=false

**Comment by aherzberg** [comment]
These outage errors are from planned EVSS maintence windows that go a couple hours past the time they are scheduled for. For example, the latest window was for `"external_service"=>"evss", "start_time"=>Sun, 02 Jun 2024 01:00:00.000000000 UTC +00:00, "end_time"=>Sun, 02 Jun 2024 04:00:00.000000000` but we got a large number of these errors at `Jun 04 04:20:58.971` 20 minutes after the end time of the window. 

All our windows look to be mapping properly to disability rating endpoint. I won't bring this to EVSS's attention since it seems better for the window to run a little over then to over estimate and just have that much longer the users can't use the feature. EVSS is in the process of being phased out as well.

I've set the error to be muted. Closing.
