### ISSUE TITLE
BUG - Sev-3 - All - SM inbox count is not going down/unread dot not going away if you open and close the message fast enough

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8577]
## What happened?

This was caught on the HSP branch due to the cache stale time increasing but occasionally if you enter and exit a message quick enough after it loads its not being registered as read and the inbox count is not going down.  

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Make or have someone make a lot of messages for user +226
2. Go into the message inbox and select an unread message.  As soon as it loads back out into the inbox.  Notice occasionally the unread dot/inbox count does not go away. 

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by bischoffa** [comment]
Dropped to Sev-3 based on discussions with Rachael and comments from Theo/Dylan.

**Comment by bischoffa** [comment]
Based on discussions here are the next steps: 
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a4d88986b75ff4b01cd9805e753b6593e2b4cdd/image.png" alt="image.png" />

**Comment by Sparowhawk** [comment]
@rbontrager I just tested this with the messages that you loaded for me.

There are currently 3 scenarios I found.

1. The message is still fetching when the user navigates back to the previous screen. This results in the message not being marked as read.

2. The message is fetched and you navigate to the previous screen where you see the status update correctly to read, requires a little time to sync either on the previous screen or the view message screen due to looping through the messages and manually setting the query data, but the screen does update correctly.

3. Similar to scenario 2, but before the data is sync'd you navigate to another unread message. This then causes a sync issue and then results in the 2nd message being marked as unread.

Previously this was all set in the SM slice management, meaning that all that was required was the api call so it happened even if the user backed out while the api was loading, which also likely eliminates scenario 3 from occurring as well.

So the current question is should we actually mark a message as read instantly or require the message to be fetched before we mark it as read?

Instantly would be most in line with how our old slice code worked, but not necessarily the correct way to do it. This also would determine how I fix this in the code.

@ala-yna

**Comment by bischoffa** [comment]
Follow-up Slack thread https://adhoc.slack.com/archives/C067S0FRP0C/p1715805650763619

**Comment by Sparowhawk** [comment]
After talks at standup.

For scenario 1 it correctly doesn't mark the message as read and must wait to be fetched before it is marked as such
For scenario 2 it does correctly mark the message as read as it waits until it is fetched and syncs the data

Scenario 3 is the one that needs to be fixed in this ticket

**Comment by rbontrager** [comment]
Verified that the SM inbox count goes down and the message appears as read if you open and close the message right after it loads.  Verified that I'm no longer seeing the SM inbox count as -1.  Approved by QA.
