### ISSUE TITLE
Componentization - Community care appointments - Detail View

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8605]
## Description 
As an engineer, I want create and reuse different standardized components for appointments, so that it will easier for other teams to start working in appointments and the different appointment types can be more aligned.

Specific details of the components needed can be found in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=402791918) (see columns F, G, H on "Details screen section" tab and also "VA Community Care - Details" tab as needed) and the design specs can be found in [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?node-id=2677-2809&t=DREGEQufkX5Vcl87-4)

**Note: for Community Care appointments, please be sure to use the provider location, not the associated VA facility location.**

As part of this story we want to: 
- Create new components that are needed for confirmed, past, and canceled, **and pending** Community Care appointments
- Plug in any pre-existing components
- Update end to end tests
- Update headings to match [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?node-id=2677-2809&t=DREGEQufkX5Vcl87-4) file
- VQA with content/design

## Acceptance Criteria

-  [ ] New components have been created
-  [ ] Existing components have been brought in
-  [ ] E2E tests have been updated
-  [ ] VQA by content
-  [ ] VQA by design

**Comment by alexandec** [comment]
Approval from content and design: https://adhoc.slack.com/archives/C067S0FRP0C/p1717542786392799

**Comment by rbontrager** [comment]
@alexandec After creating a pending CC appt in Judy and talking to Misty there was a slight change to the spreadsheet that requires some code changes.  The field needed under "Details you'd like to share with your provider" needs to be changed to whatever is in the [comment] and not [reason].

**Comment by alexandec** [comment]
@rbontrager I've updated the AppointmentReasonAndComment component so that for for pending CC appointments only (Canceled Pending, Pending, and Past Pending), it shows the comment field instead of the reason field

**Comment by alexandec** [comment]
@rbontrager I figured out the issue with the cancel button. Pending appointments with no cancel ID were still showing the cancel button, but the cancel button won't work without a cancel ID. I made a change so the cancel button is hidden for pending appointments with no cancel ID. This is the same approach we take for other types of appointments. I tested with Judy on staging since she has a pending appointment with no cancel ID.

I don't know if you're able to create appointments with and without cancel IDs on staging, but that would be the ideal way to test this. Alternatively you could intercept the API response in Charles and add/remove the cancel ID to test this.

**Comment by rbontrager** [comment]
Everything looks good outside of the following issues:

- CC Provider Name for non pending CC appts is not appearing on mobile. BE ticket [8806](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8806) has been made to address this.
- CC Provider Address for pending CC appts is not appearing on mobile. BE ticket [8852](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8852) has been made to address this. FE work will eventually be required and is addressed in ticket [8854](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8854)
- CC VA scheduling facility name is not coming in for pending CC appts on mobile. BE ticket [8861](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8861) has been made to address this.
- Cancel request button is not appearing for Pending CC Requests.  A [thread ](https://dsva.slack.com/archives/CMNQT72LX/p1719242133353629) is currently being discussed but it sounds like there may be an upstream bug somewhere and because of web's logic they never caught it or we have a BE bug that needs to be done. 

@ala-yna Please sign off that you acknowledge these bugs and confirm you still want this ticket to be merged with them.

**Comment by ala-yna** [comment]
Thank you for the write up and follow up tickets. I agree with the decision to move this ticket forward knowing that there is follow up work to be done.
