### ISSUE TITLE
Device Management - Request Device for Brea 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8704]
**Description:**

As Mobile Program, I want to assign Brea a device for testing. Ideally use one in our existing roster, if not okay with purchasing a new one. 

[
Slack Thread](https://adhoc.slack.com/archives/CU2Q76NPR/p1716476325599359)
<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1JQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d7a81a5e7d9008b4d9477bb476c4e7224cb27ed/image.png" alt="image.png" />

**Comment by DJUltraTom** [comment]
At this point we don't appear to have any "spare" iOS devices in our lineup, If we can send Brea the iPad or iPhone SE listed in the email @seheart recieved from bill,  I think that would work great and we can update our inventory sheet to reflect that devices addition to our inventory. otherwise I'm happy to start the procurement process for a new iOS device.

**Comment by DJUltraTom** [comment]
Surmising from Slack conversation:
We will request a new (to us) iOS device for @brea11y to use.
@drjecker can you please comment on this ticket what device we would prefer Brea to have?
Once we have that info I will start the requisition process (on Monday after I return to the office)

**Comment by DJUltraTom** [comment]
@drjecker feel free to unassign yourself after adding your comment

**Comment by drjecker** [comment]
Checked in with @brea11y on this. The only preference is she would like something that will be able to update to iOS 18 when that is released since they are adding a bunch of new accessibility features. Believe that means we could likely go as old as iPhone 11 or any iPad that was released after 2019 since Apple will provide OS updates for about 5 years. Although something newer would last longer. Other than that no preference - although I think we generally like to have some variety so that from a team perspective we're covering a breadth of devices. Let me or Brea know if you have further questions!

**Comment by DJUltraTom** [comment]
upon further analysis we have an extra unused iphone 13 that I propose we factory reset and send to Brea.

**Comment by drjecker** [comment]
That sounds good to me!

**Comment by DJUltraTom** [comment]
Closing this ticket as the current plan is for @rbontrager to bring the phone to the onsite and hand off the iphone to @brea11y If this doesn't happen we will request a shipping label for the device.

**Comment by brea11y** [comment]
That sounds great to me! Thanks so much Tom and Rachael!
