### ISSUE TITLE
Investigate Why Maintenance Windows Aren't Respected Sometimes

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8841]
This may be a combo FE/BE ticket. There was a datadog alert that cause a [Watchtower incident](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/119). It SHOULD have been prevented by an existing maintenance window, but it wasn't. This ticket is to confirm BE is correct, and then push it along to FE

Relevant Slack Thread: https://dsva.slack.com/archives/C021WCL114J/p1718644410249739

**Comment by aherzberg** [comment]
Recreated the event in specs and we are reporting the window. Asking FE if it could be the app side of things: https://adhoc.slack.com/archives/C0212B872MT/p1718904545695829.

**Comment by aherzberg** [comment]
FE has only recently made an update to block all calls during maintenance windows on may 28th. Unfortunately It's hard to tell exactly what versions are making that calls since we get a build number in the logs instead of a build version and the build number can be shared over multiple versions and over ios vs android. It looks like 1630 build number that was the top offender (see slack convo from ticket description) has at least one build that was the day before this blocking api call change was made. I also found another evss event on jun 8th that had dramatically less requests but still had some requests. so this wasn't just a one time event. I think this was only just now brought to our attention because of some coincidental factors that made the perfect storm .

**Comment by aherzberg** [comment]
created ticket to be picked up to make sure assumptions here are verified: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8875

**Comment by aherzberg** [comment]
<img width="1906" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e95061732059a23345b2824c577201118ffef71f/Screenshot%202024-06-21%20at%209.17.23%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 9.17.23 AM.png" /> May 23rd event

June 14th event (event that kicked off ticket) <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1DQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e1d4cee79de98bfc65a445b9ac0c10f4926e40/Screenshot%202024-06-21%20at%209.32.35%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 9.32.35 AM.png" /> Note that every request made ended in error.

**Comment by aherzberg** [comment]
<img width="1906" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e95061732059a23345b2824c577201118ffef71f/Screenshot%202024-06-21%20at%209.17.23%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 9.17.23 AM.png" /> May 23rd event

June 14th event (event that kicked off ticket) <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1DQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e1d4cee79de98bfc65a445b9ac0c10f4926e40/Screenshot%202024-06-21%20at%209.32.35%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 9.32.35 AM.png" /> Note that every request made ended in error.
