### ISSUE TITLE
Investigate Messaging 400 Error

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8876]
Thanks to our new errors monitor, we were able to catch the first new error coming through after an update https://vagov.ddog-gov.com/monitors/213410?group=%40error.file%3A%2Fapp%2Flib%2Fcommon%2Fclient%2Fbase.rb&from_ts=1718973110000&to_ts=1718974310000&event_id=7628788609514590216&source=monitor_notif

This ticket is for investigating the error

```
Mobile::V0::Messaging::ServiceException: BackendServiceException: {:status=>400, :detail=>&quot;Attachment scan failed&quot;, :code=>&quot;VA900&quot;, :source=>&quot;&quot;}
```

**Comment by kpethtel** [comment]
Closing because this is a 400 error, not a 500 error. I believe the new issue monitor does not do what we thought it would. I think there's still value in it, because it alerts us to new ways upstreams fail, but this error is a normal, expected error. I've created a [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9044) for creating a 500 error monitor.
