### ISSUE TITLE
Update App Store Images for Appointments

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9041]
## Description 
As the Veteran, I want all the app stores/pages to accurately reflect the most recent changes in the app so that I know what to expect before going into the app. 

### Note: We want to make sure these changes are coordinated with the App Store changes that Global is making for HSP.
As part of this story we want to: 

  
Determine what, if any, changes are needed to Apple, Google and VA.gov App Store pages
-  App Store images related to appointments
-  App Store app description needs updated (related to appointments)

## Acceptance Criteria
  
- [x]  Create image for [Apple Store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596?platform=ipad) for iPad
- [x]  Create image for [Apple Store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596?platform=iphone) for iPhone
- [x]  Create image for [Google Play Store](https://play.google.com/store/apps/details?id=gov.va.mobileapp&hl=en_US&gl=US) for Android phone
- [ ]  Create image for [VA.gov app page ](https://mobile.va.gov/app/va-health-and-benefits) using iPhone images
- [ ]  Create new app description for [Google Play Store](https://play.google.com/store/apps/details?id=gov.va.mobileapp&hl=en_US&gl=US)
- [ ]  Create new app description for [Apple Store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596?platform=iphone)
- [ ]  Create new app description for [VA.gov app page](https://mobile.va.gov/app/va-health-and-benefits)
- [ ]  Create new App Store Whats New description for [Google Play Store](https://play.google.com/store/apps/details?id=gov.va.mobileapp&hl=en_US&gl=US)
- [ ]  Create new App Store Whats New description for [Apple Store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596?platform=iphone)
- [ ]  Sent Mobile.Va.Gov an email and Microsoft Teams communication with Mobile's update request
- [ ]  Flagship PM to validate any app store (image, content) changes 
- [ ]  Update [alt text for Va.gov app page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management%20/Go%20to%20Market/VA.Gov%20App%20Store%20Page/Images%20In%20Use/Alt%20Text%20Image.md)

## Notes 
- All work to be done before the end of the sprint that the feature is going out
- Some parts have a longer lead time (Va.gov App Marketing Page) so please prepare accordingly
- Whats New In-App Alert box content is not included here as its not part of the app store - see separate ticket template "In-App Whats New Content - Feature Name - Release" ex [8833](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8833) 
- Any questions please reach out to Release Manager 

### Images
- Includes: iPad, iPhone and Android Phone (and a description image) 
- Process for [Updating the App Stores](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Updating%20the%20App%20Stores/)
- Historically - UX creates the images backed on this [process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Updating%20the%20App%20Stores/#designer-update-the-app-store-images) then Flagship PM validates the images and then works with their FE to submit the PR to update the images
- Images should be the same across Google, Apple and Va.Gov
- UX to create a new folder with YYYY Mon and Feature in this [Google Drive](https://drive.google.com/drive/folders/1t_WOjaZkJKNR9oXEMczjtIePAFef2ym6)
- Note if new feature is added then may need to consider how we list them in the first image which contains a list of features "Use this app to:"
- Work is done outside of the Release Ticket process
- As of June 2024 - new images need to be compressed through something like ImageOptim per Tim before being added into the repo to remove any metadata that might be bloating the files
- [Process doc for Update Va.Gov App Store ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/releases/Va.Gov%20APp%20Store)

### Content
- Inclues: App Store Whats New and App Description 
- Content will create the test for Whats New App Store (if we do not want to use "We added general improvements and fixed a few bugs.")
- This change is required for the Release process - notify Release Manager change is coming and when its done 
 

### Va.Gov Marketing Page
- Its a VA Marketing Page that will need to be updated by Flagship PM and has its own [process](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management%20/Go%20to%20Market/VA%20Call%20Center%20Process)
- Images need to be stored in [Images in Use Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management%20/Go%20to%20Market/VA.Gov%20App%20Store%20Page/Images%20In%20Use) as VA pulls images from here

 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic
- [ ] Notify Mobile Release Manager at least 1 sprint ahead of implementation date

**Comment by ala-yna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9041?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by Sparowhawk** [comment]
@brea11y added the 3 screenshots to https://drive.google.com/drive/folders/1RdW9zwKs6savg8Eg96M556unwV_9fz8y

Note the ipad one is a 13inch, I couldn't find an available simulator anymore that had 12.9inch resolution but that should be close enough

**Comment by bischoffa** [comment]
@brea11y looks like we will need to cherry pick these 3 and combine with Global's HSP screenshots as both are going out at the same time.

**Comment by brea11y** [comment]
@bischoffa – I had the same thoughts. Ameet added the HSP app store image updates to my current sprint work, so I figured the app store image updates would all likely go out together. I'm going to go ahead and pull in Appointments updates for now and will get those exported and ready for Alayna to review. When we get the HSP screenshots, I'll export those separately for Ameet's approval.

**Comment by brea11y** [comment]
@Sparowhawk – The iPhone screenshot is great. Is it possible to get another screenshot of the iPad? There is an error at the bottom that is covering the footer navigation bar (attaching a screenshot). Also, in the Android screenshot, could you turn off the status bar and the Android navigation at the bottom so that the footer navigation bar in the app is hugging that bottom edge of the screen? Attaching examples of what is currently in the app store today for appointments vs. what it would look like with the current screenshot that is in the Google Drive. Thank you!!!

![iPad screenshot with the current screenshot used](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/f40117d8-62e5-43d5-ab96-2960140c2c95)
![Current appointments app store image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/20c4d666-9c42-4c9b-a6ff-8dd49a462b64)
![Appointments app store image with current screenshot](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/2ddc22ef-dda0-46ad-9017-c0922173f2cf)

**Comment by bischoffa** [comment]
@brea11y thoughts on adding these points to the Doc Site App Store page?

**Comment by brea11y** [comment]
@bischoffa – If you are referencing the Android screenshot points, Narin provided pretty detailed instructions [on the doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Updating%20the%20App%20Stores). @Sparowhawk – They may be helpful. 🤞🏼

**Comment by Sparowhawk** [comment]
@brea11y @bischoffa iPad is updated

**Comment by Sparowhawk** [comment]
@brea11y @bischoffa Android is updated

**Comment by brea11y** [comment]
Hi @ala-yna – The images have been added [to the Google Drive](https://drive.google.com/drive/folders/1B_jjWrYODUtsCnwL_ovCHkWeC_ZRhzJ2?usp=sharing) in their corresponding folders. I am also uploading them here for your approval. If there are no updates needed, they have been optimized and are ready to add to the app stores. 

_Also noting that since we are also updating the app store images for HSP this sprint, the updated images for appointments are currently the only app store images in the Google Drive folders._

iPad 12.9:
![iPad app store image for appointments](https://github.com/user-attachments/assets/bd0f7247-8796-4c09-889c-50dab30d6263)

iPhone 5.5:
![iPhone 5.5 app store image for appointments](https://github.com/user-attachments/assets/d716e871-4258-4e00-a4fc-11a08757309a)

iPhone 6.7:
![iPhone 6.7 app store image for appointments](https://github.com/user-attachments/assets/017ac6ad-e3e3-4360-9dda-d0c479ae3bcb)

Android:
![Android app store image for appointments](https://github.com/user-attachments/assets/6a978150-e6b1-44ca-a171-2a2bae4c6870)

**Comment by ala-yna** [comment]
These look great, thank you @brea11y and @Sparowhawk for all your quick work on this!! Looking through the screenshots, I'm wondering if we should think about picking a different test appointment to use - I get that this is the best 1:1 replacement for what we currently have, but I don't think Community Care appointments (especially with this `Details you shared with your provider` test data) are the best representation of this work. I'll circle back with the team on Monday, I know it's late on a Friday.

**Comment by ala-yna** [comment]
@brea11y Let's go ahead and get these in! I can make a follow up ticket to use a different appointment later on.

**Comment by brea11y** [comment]
@ala-yna – That sounds great. I have updated the Google Drive folders with the rest of the app store images and they are currently pending Ameet's review and approval. I believe once we get that, all of the app store images will be ready for release.

**Comment by ala-yna** [comment]
Amazing, thank you!

**Comment by Sparowhawk** [comment]
@ala-yna is this ticket done from an engineering perspective?
