### ISSUE TITLE
Update Demo Mode to Align Better Align w/ Current App

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9205]
**Description:** 
As VAHB, I would like to update the VAHB Demo Mode so that it better aligns with the current time and functionality so that those using demo mode knows it been updated and it works just like the app should 

**Notes:**

- Derived from ticket [7699](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7699#issuecomment-2253695551)
- Add it to QA and Release team though we don't have the ability to do this - so that we can coordinate with teams to get this work completed ; may need to split out the tickets 

**ACs:**

- Determine if we need saved data for Direct Deposit + if so add 
- Determine if we need saved data for Preferred Name + if so add 
- Mail in messages are from 2021 - can we update to make it more timely 
- Payment history is from 2016 - can we update to make it more timely

**Comment by TKDickson** [comment]
- Preferred name and direct deposit - no we do not need data, not adding. Changes you make to those will 'persist' during the demo mode session (you can add a bank account, leave and come back to the DD page, and it's still there). We don't need either of them populated when you first get to the page.
- Payment history updated to 2023 and 2024 (instead of 2016 and 2017)
- Messages updated to 2024
- Updated detox tests to account for both of the year changes above
