### ISSUE TITLE
BUG - Low - All - Veteran reported confusion about Oracle Health alert

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va-mobile-app#9214]
## What happened?
A Veteran logged into the VA Health and Benefits app and it showed their preferred location as James A. Lovell in North Chicago. Their main treatment facility is Dayton VAMC, so seeing Lovell caused confusion. 

After OCTO spoke with the staff reporting the scenario, we hypothesized that it was the Oracle Health alert wording that caused this confusion. We verified a registration at Lovell, but see no other interactions at the site. Hence, the understandable confusion. Details in this [Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1720617556765429) thread.

Originated as an open White House complaint, but the complaint was able to be closed already.

## Specs:

- Device: Unknown
- OS: Unknown
- User Account: Unknown
- Accessibility State: Unknown

## Desired behavior

- Review alert for possible content enhancements.

## Acceptance Criteria

- Work with OCTO Health to estimate impact more.
- Review web alert content and the above scenario, then generate a proposal.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [x] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by mistymg** [comment]
Pointing as a 3 as I believe this will take some back and forth/conversations.

**Comment by mistymg** [comment]
Chatted with Laura W. today and landed on a solution. Will write up and share later.

**Comment by mistymg** [comment]
Unblocked: Heard from Danielle; will post my recommendations in the ticket by end of day

**Comment by mistymg** [comment]
@kristenmcconnell @ala-yna I'm ready to make a recommendation for this bug.

Based on the ticket description and the Slack thread, it's not super clear what might have caused the confusion. (Ticket mentioned "preferred location" but we have no such preferences in the app. And this might have also occurred during the very tricky Lovell transition.)

My best guess is that the user was confused by the OH alert that used to appear on the Health category screen and/or Appointments feature screen. (I say "used to" because with the launch of our new home screen, the OH alert that appeared on the Health category screen was updated after this bug.)

Specifically, my gut is that the wording "Our records show you're registered at..." is indeed confusing. If not read carefully, it could be assumed that we're showing a list of **_all registered facilities_** (when it's just OH facilities the user is registered at). CAIA agreed with me, and we worked to update the wording.

My suggestions:

- Change copy [per this Figma](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1358-129&t=th5E9v41XHYBbPqk-4) for OH alerts on Health category and Appointments feature screens. 
    - All other OH alerts are fine.
    - If you want to see my train of thought, you can start [at the top of the Figma file](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1358-124&t=th5E9v41XHYBbPqk-4) a read through my reasoning.

- Only use copy variations for when we have (1) an OH-only user and (2) a mixed user (OH and Vista). 
    - Right now we have variations for when a user is registered at 1 OH facility, >1 OH facility, or is a mixed user. CAIA and I agree for simplicity that we can stop distinguishing between 1 and >1.

If you have any questions or need help translating my recommendations into implementation tickets for Eng., let me know!

**Comment by kristenmcconnell** [comment]
@mistymg I completely agree with the analysis that "Our records show you're registered at..." might be the area causing confusion. I like the propose wording. I added one suggestion in the Figma file.

**Comment by mistymg** [comment]
@kristenmcconnell That was really helpful and valid feedback! I tweaked the wording a bit in a [v2 section of the Figma](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1427-101&t=MlZt4aItY6s4pyHe-4). How about that?

**Comment by kristenmcconnell** [comment]
The V2 revisions look great. Thanks.

**Comment by mistymg** [comment]
@kristenmcconnell Made one final tweak for OH-only users in [the Figma](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o?node-id=1427-101#949292331) after chatting with Laura Willwerth. If you're good with this, I'll make implementation tickets for Engineering.

**Comment by mistymg** [comment]
Since copy changes have been approved, I created [this engineering ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9597) to implement changes.
