### ISSUE TITLE
BUG - Sev 3 - All? - In App Review Event can trigger before/on top of file open

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9248]
## What happened?

https://github.com/user-attachments/assets/7f659d08-ee6a-43a7-a393-2c135241779a

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

-reset in-app review count.
-download 7 letters in staging.

## Desired behavior

-don't interrupt user flow with an in app review request.

## Acceptance Criteria

-^it doesn't.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

low, low

- 3 - Low
- 2 - High
- 1 - Critical

4

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
The in-app review prompt popup is now appearing *after* closing the file viewer for a letter (instead of on top of the letter) in Android. It's not possible to test in iOS ([will not appear in builds distributed with test flight](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview)) but @dumathane did say it was working correctly when he checked on the emulator. Hopefully monitoring the event from #9244 will help us spot issues with iOS in production, in the future.

**Comment by TKDickson** [comment]
No testing in develop needed; closing
