### ISSUE TITLE
Add event: Submit evidence button click

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9275]
Add a click event to the new [Submit evidence] primary button. This button is a new addition to the experience, through the work that has occurred within this epic (8688).

**Comment by wavelaurenrussell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9275?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by Sparowhawk** [comment]
@wavelaurenrussell @OVezeamama this one is vama_claim_submit_tap

**Comment by rbontrager** [comment]
Verified that the vama_claim_file_request logging statement happens in the sim when the user clicks to open claim details of a claim in step 3 with file requests.  Verified that vama_claim_submit_ev logging statement happens in the sim when the user clicks to open claim details of a claim without file requests and only happens when the submitEvidence flag is turned on.  Verified that vama_claim_submit_ev is no longer logging twice for a claim in step 3 without file requests and is no longer logging with vama_claim_file_request  for a claim in step 3 with file requests.  Verified that a logging statement is displayed when the user clicks the submit evidence button. We cannot view analytics in staging so this is as much as can be verified.  Approved by QA.
