### ISSUE TITLE
BUG - sev-3 - Analytics Incorrectly Firing for Messages Screenviews

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9282]
Description of problem: The ViewMessageScreen Screenview seems to have been incorrectly firing some time in the past 6 months

**Comment by TKDickson** [comment]
@ajsarkar28 a problem with any messaging-related analytics would be a H&B bug ticket, not a global one. I'm switching the labels on this FYI.

**Comment by OVezeamama** [comment]
<img width="203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3M5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbd14a848630c83952354e666e5fab75f69e673b/image.png" alt="image.png" />

Above is data showing since app version 2.18.0, there hasnt been any counts from `ViewMessageScreen`
@dumathane @rbontrager

**Comment by OVezeamama** [comment]
Additional data `ViewMessageScreen` <img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e35776e704ce9e4ec8d07d4347ee43c478e475/image.png" alt="image.png" />

**Comment by dumathane** [comment]
![image](https://github.com/user-attachments/assets/7e32e25d-e3a4-4512-a890-e52d1d16f9a0)
We renamed the screen from ViewMessageScreen to ViewMessage, so we'll need to account for both names when capturing analytics.
