### ISSUE TITLE
Discovery: Available travel pay APIs

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9295]
Find and document the available travel pay APIs that we could possibly integrate with. I would start by reaching out in the travel-pay channel in dsva

**Comment by aherzberg** [comment]
Travel Pay API current documentation is not hosted anywhere atm but I've attached a local up to date copy here: [travel-pay-api-swagger (3).txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0YyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ea71eeb71be8f8860237171003c77f3d9361816/travel-pay-api-swagger%20%283%29.txt) . Copy and paste the contents into https://editor.swagger.io/ to make it more readable. The API has got much bigger since we last investigated this and it looks like we'll need to use the majority of these endpoints. 

There is an existing Travel pay service/controller in vets-api at `modules/travel_pay/app/controllers/travel_pay/claims_controller.rb` but it only is integrated with one of the endpoints. Kevin Duensing said though that starting next week that plan on adding more of the api endpoints to that service. 

Note that the API uses `Claims` and `Appointments` but I've confirmed that the claims are not the same claims we already have in the app they are stored elsewhere so we cannot reuse our existing claim endpoints. The Appointments was a bit unclear, It sounds like we can create a travel pay claim off of the appointments we get from VAOS but its not a comprehensive list so we should probably still integrate with the endpoints that allow the creation of a travel pay claim appointment to fill any gaps. 

the diagram listed here, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/submit-claim/integration/work-streams.md, should give a good idea of the flow of these endpoints. When pointing this feature, I think it'll be comparable to the appointment scheduling effort with 6-8 endpoints needing to be hit in sequence to submit a claim.  

See convo with travel team here: https://dsva.slack.com/archives/C05Q9HH47PS/p1724174272192819
