### ISSUE TITLE
Update RN from 0.73.8 to 0.75.x (latest)

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9430]
As of creating ticket the latest is 0.75.2

This ticket is for the purpose of upgrading our RN dependency from 0.73.8 to the latest available in preparation for a pending update from design system team for the snackbar.

App should function as is and unit tests/detox should still work afterwards

Process goes upgrade from 0.73.8 to 0.74.0 then to latest 0.74.x version then 0.75.0 then to 0.75.x(the latest available)

Things to consider is the new way to handle the react native bridge introduced in 0.74 for native modules

**Comment by DJUltraTom** [comment]
@Sparowhawk for QA to validate this change is the AC that "E2E detox tests do not fail"? or is there additional manual testing that will need to occur?

**Comment by Sparowhawk** [comment]
@DJUltraTom QA validation previously was to finish the additional testing that is normally done that detox doesn't cover.

I have already checked unit tests and they all passed

Detox iOS all passed, Android passed all except messages which said was a timeout issue. So if you want to rerun messages in detox that can be done. 

Here are the runs for. both

https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10636519873

https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10636522285

So all that is left is the normal testing typically done on RC branches outside of detox/unit tests that covers the things that detox doesn't.

**Comment by DJUltraTom** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/5899&group_by=cases:section_id&group_order=asc 
manual tests look good. 
the detox test for android messages has failed again, I've asked @rbontrager to investigate. and if the failures are detox related and not build related this ticket is good to be closed and the PR approved.

**Comment by rbontrager** [comment]
@Sparowhawk I was messing around to see if I could fix messages in your PR to no avail.  Android is also failing both in github actions and locally on yarn e2e:android-build with the following error (you can see it on any detox run under bundle android app you make with your branch [here](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10744266541/job/29800863716):

`Execution failed for task ':react-native-image-picker:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.75.2] /Users/runner/.gradle/caches/8.8/transforms/19aaa080b25980d3c2835a59d4e16872/transformed/react-android-0.75.2-debug/AndroidManifest.xml as the library might be using APIs not available in 21
the instrumented classes might contain corrupt stack frames. Make sure the
dependencies that contain these classes are on the runtime or the provided
classpath. Otherwise, the jvm might fail to load the corrupt classes at runtime
when running in a jvm environment like unit tests.`

**Comment by Sparowhawk** [comment]
I updated react native image picker from 7.1.1 to 7.1.2 which is supposed to fix support for RN 0.74+

**Comment by Sparowhawk** [comment]
fixed the android yarn errors

waiting on e2e tests again to see what still needs to be fixed

**Comment by rbontrager** [comment]
Verified that all test cases passed in the regression test (both manual and automated).  Test run can be found [here](https://dsvavsp.testrail.io/index.php?/runs/view/5942&group_by=cases:section_id&group_order=asc).  Approved by QA.
