### ISSUE TITLE
Even more Icon migrations

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9816]
Photo add(upload photos screen)
Photo Upload(veteran status screen, not used)
Left Chevron
Right Chevron

**Comment by theodur** [comment]
@Sparowhawk @rbontrager You may want to sync with Brea and Jessica to make sure the colorand theme of the icons are correct when this is ready for visual QA. With the component library's icon, we're supposed to be switching away from the duotone theme. More context in this [Slack thread](https://adhoc.slack.com/archives/C063KLSMVAR/p1730740578971619).

**Comment by rbontrager** [comment]
@theodur @wavelaurenrussell has been doing the VQA on the other icon tickets.  She might be best qualified to do the initial one here as well.

**Comment by brea11y** [comment]
Hey all. Rachael looped me in and asked me to do a quick VQA of the three icons in the list above (since the photo add in VS isn't visible). I took a look in dark and light mode on iOS (with my Android test device, I always see the old duotone icons) and they look great on my end. 

I do just want to note here that for the USWDS icons, we should never have to manipulate or override them. That doesn't appear to be happening with any of these icons, but I do think that it is important to note that each icon should only have one color assigned for dark mode and one color assigned for light mode. Using the add photo / plus icon as an example, we should be using a darker shade of blue in light mode and a lighter shade of blue in dark mode. This particular USWDS icon does still have the circle shape, but it has the plus sign cut out of it in the center so that it will always show the background color that it is sitting on as the color of the plus sign.

With that being said, the plus icon does appear to be the new USWDS icon and the shades of blue used in dark and light mode appear to be correct.

I also took a look at the chevrons and they also appear to be the new USWDS icons. I checked the back link for the feature/child screens, pagination buttons, list items, link rows, etc. and they all appear to be correct and used as intended.

The only other thing that I do want to note about the new icons is that they are Material icons. The old duotone icons that we used previously are from FontAwesome. With the older FontAwesome icons, they were cropped pretty closely around the icons themselves. Material icons have built in padding around them that varies based on the icon's shape / dimensions. For some icons, like the chevron, there is now additional space to the right and left of the icon (other icons we may have extra space above and below) that was not present in the old icon. The reason I bring this up is because for some icons, we may have to make some additional adjustments to account for the extra padding that is built into the new icons that the older icons did not have. 

For example, if one of our old icons was cropped tightly around the icon itself and we added 5px of space between it and the copy so that the two elements didn't touch, when we swap that same icon out with one of the new icons, that new icon might have an additional 2-3px to the right and left that the old icon did not have. This would increase the gap / space between the copy and the icon itself, which might throw things off visually. I would recommend always having a designer VQA the icon swaps and be prepared to make some of those adjustments if they recommend it.

**Comment by rbontrager** [comment]
@Sparowhawk I know I reached out to Lauren originally about the right chevron location but it sounds like Brea is probably the more informed designer for this stuff now.  With that being said would it be possible to trim the padding so we are no longer wrapping our menu items for stuff like claims. 

<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9JQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--039f1056e883d6133e82c1dac05557c3be777d5c/Screenshot_20241114-084011.png" alt="Screenshot_20241114-084011.png" />

**Comment by wavelaurenrussell** [comment]
> [@Sparowhawk](https://github.com/Sparowhawk) I know I reached out to Lauren originally about the right chevron location but it sounds like Brea is probably the more informed designer for this stuff now. With that being said would it be possible to trim the padding so we are no longer wrapping our menu items for stuff like claims.
> 
> <img alt="Screenshot_20241114-084011.png" width="389" src="https://camo.githubusercontent.com/12bfba3bde7046329219b765efc6c9dd3934df9bb97a41d05472c028e4a06fe4/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e69394a516e633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d303339663130353665383833643631333365383263316461633035353537633362653737376435632f53637265656e73686f745f32303234313131342d3038343031312e706e67">

In the future, we should democratize all this info, and not in GH comments. Its often unclear what QA is asking, and I also need to be looped into the specifics when it comes to design.

**Comment by rbontrager** [comment]
Checked that the icons look correct in the following places and that nothing looks amiss from an a11y perspective with voiceOver, text resizing, landscape, dark mode etc:

- Photo add(upload photos screen)
- Photo Upload(veteran status screen, not used)
- Left Chevron: Pagination, Descriptive back button
- Right Chevron. Lists, Nametags, Pagination, InLineTextWithIcons (Messages Lists), Link-rows (Contact us/Find VA location in home screen etc)

Verified that the padding around the right chevron is less than what it was and that the lists are no longer wrapping when they weren't before. Approved by QA.
