### ISSUE TITLE
CU - Utils Detox: Replace by.text with by.id

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9851]
## Proposed Change

Probably needs to wait till everything else is done but it would be nice to replace all instances of by.text (especially in the navigation functions) to by.id in Utils

**Comment by TKDickson** [comment]
OK after realizing what all changes could be made in utils, I'm going to split this ticket into three tickets instead.
- My current ticket: for things with existing IDs that we just aren't using in the utils file, replace by.text with by.id. And, if those are being defined in 'downstream' scripts, move those to this one (aka move the carousel skip button from Onboarding to utils, since we need it in utils)
- A different ticket: creating net-new IDs for things we can create IDs for, and replacing by.text with by.id for those
- Another ticket: replacing any calls that are using strings ex by.text('Remote Config') to use a constant instead, regardless if they're text or id
